const API='https://script.google.com/macros/s/AKfycbwCGKZiV57bzmspcr5W2aVF5R7SpbwEqCs911boTjJbkPYvFEZJ-QNL0iD42qrxXfT9/exec';const $=id=>document.getElementById(id);let products=[],vendors=[],pos=[],loginRole='vendor',selected=new Set(),poItems=[];const KEY='mb_vendor_session';
const session=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch(e){return null}};const token=()=>session()?.token||'';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function api(p,timeout=12000){return new Promise((resolve,reject)=>{const cb='mb_'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(t);delete window[cb];s.remove();fn(v)};const t=setTimeout(()=>finish(reject,Error('Gateway timeout')),timeout);window[cb]=v=>finish(resolve,v);s.onerror=()=>finish(reject,Error('Gateway unavailable'));s.async=true;s.src=API+'?'+new URLSearchParams({...p,callback:cb});document.head.appendChild(s)})}
function toast(m){const t=$('toast');if(!t)return;t.textContent=m;t.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.add('hidden'),3000)}
function metric(a,b){return '<div class="metric"><span>'+esc(a)+'</span><b>'+esc(b)+'</b></div>'}function active(p){return String(p.status||'').toLowerCase()==='active'}
function health(a){if(!a.length)return 0;return Math.round(a.filter(p=>p.productName&&p.sku&&p.productLink&&p.supplier).length/a.length*100)}
function csv(rows,name){const q=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(q).join(',')).join('\n')],{type:'text/csv'}));a.download=name;a.click()}
function login(){const id=$('loginId').value.trim(),password=$('loginPassword').value;if(!id||!password)return $('loginMsg').textContent='Enter ID and password.';const b=$('loginBtn');b.disabled=true;$('loginMsg').textContent='Connecting…';api({action:'login',role:loginRole,id,password}).then(r=>{if(!r?.success)throw Error(r?.message||'Login failed');localStorage.setItem(KEY,JSON.stringify(r));openPortal(r)}).catch(e=>$('loginMsg').textContent=e.message).finally(()=>b.disabled=false)}
function openPortal(r){$('loginScreen')?.classList.add('hidden');$('portal')?.classList.remove('hidden');$('logout')?.classList.remove('hidden');$('welcome').textContent=r.role==='admin'?'Administrator Dashboard':'Welcome, '+r.name;$('vendorIdentity').textContent=r.role==='admin'?'MASTER ACCESS • PRODUCTS • VENDORS • PURCHASE ORDERS':'VENDOR ACCOUNT • '+r.id;$('connection').innerHTML='<i></i>LIVE';document.querySelectorAll('.adminOnly').forEach(x=>x.classList.toggle('hidden',r.role!=='admin'));r.role==='admin'?loadAdmin():loadVendor();showSection('dashboard')}
async function logout(){try{await api({action:'logout',token:token()},5000)}catch(e){}localStorage.removeItem(KEY);location.reload()}
function showSection(n){const s=session(),isAdmin=s?.role==='admin';const adminRoot=$('adminView');if(adminRoot)adminRoot.classList.toggle('hidden',!isAdmin);const ids={dashboard:'workspaceDashboard',products:isAdmin?'adminProductsSection':'vendorView',po:isAdmin?'adminPOSection':'vendorView',vendors:'adminVendorsSection',operations:'operationsSection',profile:'profileSection'};const targets=new Set(Object.values(ids));if(adminRoot&&!isAdmin)targets.add('adminView');targets.forEach(id=>$(id)?.classList.add('hidden'));if(adminRoot&&isAdmin)adminRoot.classList.remove('hidden');$(ids[n])?.classList.remove('hidden');document.querySelectorAll('.side button').forEach(b=>b.classList.remove('active'));const nav={dashboard:'navDashboard',products:'navProducts',po:'navPO',vendors:'navVendors',operations:'navOperations',profile:'navProfile'};$(nav[n])?.classList.add('active');if(n==='po'&&isAdmin)loadPO();if(n==='vendors'&&isAdmin)loadVendors();if(n==='dashboard')drawDashboard();if(n==='profile'){if($('profileRole'))$('profileRole').textContent=s?.role||'—';if($('profileId'))$('profileId').textContent=s?.id||'—';if($('profileName'))$('profileName').textContent=s?.name||'—'}}
function setupNavigation(){[['navDashboard','dashboard'],['navProducts','products'],['navPO','po'],['navVendors','vendors'],['navOperations','operations'],['navProfile','profile']].forEach(([id,n])=>$(id)?.addEventListener('click',()=>showSection(n)));$('quickCreatePO')?.addEventListener('click',openPO);$('createPO')?.addEventListener('click',openPO);$('adminPORefresh')?.addEventListener('click',loadPO)}
async function loadAdmin(){try{const [a,v,m]=await Promise.all([api({action:'adminProducts',token:token()}),api({action:'adminVendors',token:token()}),api({action:'data'})]);if(!a?.success)throw Error(a?.message||'Session expired');products=a.products||[];vendors=v?.vendors||[];mergeMasterVendors(m);drawAdminStats();drawAdminProducts();drawDashboard();loadPO()}catch(e){toast(e.message)}}
function mergeMasterVendors(r){if(!r?.success)return;const m=new Map();(r.data||[]).forEach(p=>{const n=String(p.vendor||p.vendorName||'').trim();if(n)m.set(n.toLowerCase(),n)});const ex=new Set(vendors.map(v=>String(v.name||'').toLowerCase()));for(const [k,n] of m)if(!ex.has(k))vendors.push({id:'vendor-'+n.toLowerCase().replace(/[^a-z0-9]+/g,'-').slice(0,38),name:n,enabled:true,masterOnly:true});vendors.sort((a,b)=>a.name.localeCompare(b.name))}
async function loadVendor(){try{const [a,p]=await Promise.all([api({action:'vendorData',token:token()}),api({action:'vendorPurchaseOrders',token:token()})]);if(!a?.success)throw Error(a?.message||'Session expired');products=(a.products||[]).filter(active);pos=p?.purchaseOrders||[];drawVendor();drawPO('vendorPO',pos);drawDashboard()}catch(e){toast(e.message)}}
function drawDashboard(){const open=pos.filter(x=>!['Cleared','Completed','Received'].includes(String(x.status)));$('dashboardMetrics').innerHTML=metric('PRODUCTS',products.length)+metric('OPEN POs',open.length)+metric('VENDORS',session()?.role==='admin'?vendors.length:1)+metric('ACTIVE',products.filter(active).length)+metric('HEALTH',health(products)+'%');if($('dashOpenPO'))$('dashOpenPO').textContent=open.length;if($('dashProducts'))$('dashProducts').textContent=products.length;if($('dashVendors'))$('dashVendors').textContent=session()?.role==='admin'?vendors.length:1}
function card(p,v){return '<article class="card"><div class="photo">'+(p.image?'<img loading="lazy" src="'+esc(p.image)+'">':'<span>PRODUCT IMAGE</span>')+'</div><div class="body"><div class="actions"><label><input class="check selectProduct" data-sku="'+esc(p.sku)+'" type="checkbox" '+(selected.has(String(p.sku))?'checked':'')+'> Select</label><span class="pill ok">'+esc(p.status||'ACTIVE')+'</span></div><div class="sku">'+esc(p.sku)+'</div><div class="name">'+esc(p.productName)+'</div><div class="meta"><div><small>SUPPLIER</small><b>'+esc(p.supplier||'—')+'</b></div><div><small>VENDOR</small><b>'+esc(p.vendor||'—')+'</b></div><div><small>LANDING COST</small><b>'+esc(p.landingCost||p.price||'—')+'</b></div><div><small>QUANTITY</small><b>'+esc(p.quantity||'—')+'</b></div></div><div class="actions">'+(p.productLink?'<a class="btn" target="_blank" rel="noopener" href="'+esc(p.productLink)+'">Source ↗</a>':'')+(v?'<button class="btn" onclick="vendorUpdate(\''+encodeURIComponent(p.sku)+'\')">Update</button>':'<button class="btn" onclick="editProduct(\''+encodeURIComponent(p.sku)+'\')">Edit</button>')+'</div></div></article>'}
function drawVendor(){const q=($('vendorSearch')?.value||'').toLowerCase();const a=products.filter(p=>[p.sku,p.productName,p.supplier,p.price,p.remarks].join(' ').toLowerCase().includes(q));$('vendorStats').innerHTML=metric('ASSIGNED PRODUCTS',products.length)+metric('VISIBLE RESULTS',a.length)+metric('LISTING HEALTH',health(products)+'%')+metric('WITH IMAGES',products.filter(p=>p.image).length)+metric('ACCESS','VENDOR ONLY');$('vendorProducts').innerHTML=a.length?a.map(p=>card(p,true)).join(''):'<div class="state">No active assigned products match.</div>'}
function drawAdminStats(){const a=products.filter(active);$('adminStats').innerHTML=metric('TOTAL PRODUCTS',products.length)+metric('ACTIVE LISTINGS',a.length)+metric('INACTIVE',products.length-a.length)+metric('LISTING HEALTH',health(a)+'%')+metric('IMAGES',a.filter(p=>p.image).length+'/'+a.length)}
function filteredAdmin(){const q=($('adminSearch')?.value||'').toLowerCase(),vf=$('adminVendorFilter')?.value||'',sf=($('adminStatusFilter')?.value||'').toLowerCase();return products.filter(p=>[p.sku,p.productName,p.supplier,p.vendor,p.price].join(' ').toLowerCase().includes(q)).filter(p=>!sf||String(p.status||'').toLowerCase()===sf).filter(p=>!vf||String(p.vendor||'').toLowerCase()===vf.toLowerCase())}
function populateVendorFilter(){const s=$('adminVendorFilter');if(!s)return;const c=s.value;s.innerHTML='<option value="">All vendors</option>'+vendors.map(v=>'<option>'+esc(v.name)+'</option>').join('');s.value=c}
function drawAdminProducts(){populateVendorFilter();const a=filteredAdmin();$('adminProductList').innerHTML=a.length?a.map(p=>card(p,false)).join(''):'<div class="state">No matching products.</div>'}
async function loadVendors(){try{const r=await api({action:'adminVendors',token:token()});if(r?.success)vendors=r.vendors||[];const master=await api({action:'data'});mergeMasterVendors(master);const b=$('vendorList');if(!b)return;b.innerHTML=vendors.length?'<div class="tableWrap"><table class="table"><thead><tr><th>Vendor</th><th>Login ID</th><th>Password</th><th>Access</th><th>Action</th></tr></thead><tbody>'+vendors.map((v,i)=>'<tr><td>'+esc(v.name)+'</td><td><input class="field vendorCred" id="vid_'+i+'" value="'+esc(v.id||'')+'"></td><td><input class="field vendorCred" id="vpw_'+i+'" type="text" placeholder="New password"></td><td><select class="field vendorCred" id="ven_'+i+'"><option value="true" '+(v.enabled!==false?'selected':'')+'>Enabled</option><option value="false" '+(v.enabled===false?'selected':'')+'>Disabled</option></select></td><td><button class="btn primary" onclick="saveVendorRow('+i+')">Save</button></td></tr>').join('')}</tbody></table></div>':'<div class="state">No vendors found.</div>'}catch(e){toast(e.message)}}
async function saveVendorRow(i){const v=vendors[i],id=$('vid_'+i)?.value.trim(),password=$('vpw_'+i)?.value||'',enabled=$('ven_'+i)?.value==='true';if(!id)return toast('Login ID is required.');const r=await api({action:'saveVendor',token:token(),id,name:v.name,password,enabled});toast(r?.message||'Saved');if(r?.success)loadVendors()}
async function saveVendor(){const id=$('newVendorId')?.value.trim(),name=$('newVendorName')?.value.trim(),password=$('newVendorPassword')?.value||'';if(!id||!name||!password)return toast('Vendor ID, name and password are required.');const r=await api({action:'saveVendor',token:token(),id,name,password,enabled:true});toast(r?.message||'Saved');if(r?.success){if($('newVendorId'))$('newVendorId').value='';if($('newVendorName'))$('newVendorName').value='';if($('newVendorPassword'))$('newVendorPassword').value='';loadVendors()}}
async function loadPO(){try{const r=await api({action:'purchaseOrders',token:token()});if(!r?.success)throw Error(r?.message||'Unable to load POs');pos=r.purchaseOrders||[];drawPO('adminPO',pos);drawDashboard()}catch(e){toast(e.message)}}
function drawPO(id,a){const b=$(id);if(!b)return;if(!a.length)return b.innerHTML='<div class="state">No purchase orders found.</div>';b.innerHTML='<table class="table"><thead><tr><th>PO</th><th>Vendor</th><th>SKU</th><th>Product</th><th>Qty</th><th>Status</th><th>PDF</th></tr></thead><tbody>'+a.map(x=>'<tr><td>'+esc(x.poId)+'</td><td>'+esc(x.vendorName)+'</td><td>'+esc(x.sku)+'</td><td>'+esc(x.productName)+'</td><td>'+esc(x.quantity)+'</td><td>'+esc(x.status)+'</td><td><button class="btn" onclick="printPO('+JSON.stringify(x.poId)+')">PDF</button></td></tr>').join('')}</tbody></table>'}
function selectedRows(){return products.filter(p=>selected.has(String(p.sku)))}function selectAll(){filteredAdmin().forEach(p=>selected.add(String(p.sku)));drawAdminProducts()}function clearSelection(){selected.clear();drawAdminProducts()}
function printPO(id){const rows=pos.filter(x=>x.poId===id);if(!rows.length)return toast('PO not found.');const w=window.open('','_blank');if(!w)return toast('Allow pop-ups.');w.document.write('<html><head><title>PO '+esc(id)+'</title><style>body{font:12px Arial;padding:30px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ccc;padding:7px;text-align:left}</style></head><body><h1>Purchase Order '+esc(id)+'</h1><p>Vendor: '+esc(rows[0].vendorName)+'</p><table><tr><th>Product</th><th>SKU</th><th>Supplier</th><th>Qty</th><th>Cost</th><th>Status</th></tr>'+rows.map(x=>'<tr><td>'+esc(x.productName)+'</td><td>'+esc(x.sku)+'</td><td>'+esc(x.supplier)+'</td><td>'+esc(x.quantity)+'</td><td>'+esc(x.landingCost)+'</td><td>'+esc(x.status)+'</td></tr>').join('')}</table><script>setTimeout(()=>window.print(),300)<\/script></body></html>');w.document.close()}
function pdf(rows,title){if(!rows.length)return toast('Select at least one product.');const w=window.open('','_blank');if(!w)return toast('Allow pop-ups.');w.document.write('<html><head><title>'+esc(title)+'</title></head><body><h1>'+esc(title)+'</h1><table border="1" cellpadding="7" cellspacing="0"><tr><th>Product</th><th>SKU</th><th>Supplier</th><th>Vendor</th><th>Cost</th><th>Qty</th><th>Status</th></tr>'+rows.map(p=>'<tr><td>'+esc(p.productName)+'</td><td>'+esc(p.sku)+'</td><td>'+esc(p.supplier)+'</td><td>'+esc(p.vendor)+'</td><td>'+esc(p.landingCost||p.price)+'</td><td>'+esc(p.quantity)+'</td><td>'+esc(p.status)+'</td></tr>').join('')}</table><script>setTimeout(()=>window.print(),300)<\/script></body></html>');w.document.close()}
function renderPOVendors(){const b=$('poVendors');if(!b)return;b.innerHTML=vendors.length?'<label><input type="checkbox" id="poAllVendors"> <b>Select all portal suppliers</b></label>'+vendors.map(v=>'<label><input class="poVendor" type="checkbox" value="'+esc(v.id)+'" data-name="'+esc(v.name)+'" '+(v.masterOnly?'disabled':'')+'> '+esc(v.name)+' '+(v.masterOnly?'<span class="pill">ACCOUNT NEEDED</span>':'<span class="pill ok">READY</span>')+'</label>').join(''):'<div class="state">No vendors available.</div>';$('poAllVendors')?.addEventListener('change',e=>document.querySelectorAll('.poVendor:not(:disabled)').forEach(x=>x.checked=e.target.checked))}
function selectedPOVendors(){return [...document.querySelectorAll('.poVendor:checked')].map(x=>({id:x.value,name:x.dataset.name}))}
function renderPOItems(){const b=$('poItems');if(!b)return;b.innerHTML=poItems.length?'<div class="panel"><div class="sectionTitle"><b>PO LINE ITEMS</b><span class="pill">'+poItems.length+' PRODUCTS</span></div>'+poItems.map((p,i)=>'<div class="poRow"><div class="field" style="margin:0">'+esc(p.productName)+' <span>['+esc(p.sku)+']</span></div><input class="field" type="number" min="1" value="'+esc(p.quantity||1)+'" data-i="'+i+'"><button class="btn" data-remove="'+i+'">×</button></div>').join('')+'</div>':'<div class="state">Add SKUs to build the purchase order.</div>';b.querySelectorAll('[data-i]').forEach(x=>x.onchange=()=>poItems[+x.dataset.i].quantity=x.value);b.querySelectorAll('[data-remove]').forEach(x=>x.onclick=()=>{poItems.splice(+x.dataset.remove,1);renderPOItems()})}
function openPO(){if(session()?.role!=='admin')return;poItems=[];renderPOVendors();renderPOItems();if($('poLookup'))$('poLookup').textContent='';$('poModal')?.classList.remove('hidden')}
async function addPOSku(){const sku=$('poSku').value.trim();if(!sku)return;if(poItems.some(x=>String(x.sku)===sku))return toast('SKU already added.');$('poLookup').textContent='Looking up…';try{const r=await api({action:'purchaseLookup',token:token(),sku});if(!r?.success)throw Error(r?.message||'Product not found.');poItems.push({...r.product,quantity:r.product.quantity||1});$('poSku').value='';$('poLookup').textContent='Added '+r.product.productName;renderPOItems()}catch(e){$('poLookup').textContent=e.message}}
async function createPO(){const targets=selectedPOVendors();if(!targets.length)return toast('Select at least one supplier panel.');if(!poItems.length)return toast('Add at least one product.');const b=$('poCreate');b.disabled=true;b.textContent='Creating…';let ok=0;try{for(const v of targets){const r=await api({action:'savePurchaseOrder',token:token(),vendorId:v.id,vendorName:v.name,items:JSON.stringify(poItems.map(p=>({sku:p.sku,quantity:p.quantity,remarks:p.remarks||''})))});if(r?.success)ok++}toast(ok+' supplier panel PO(s) created');if(ok){$('poModal')?.classList.add('hidden');await loadPO()}}finally{b.disabled=false;b.textContent='Create / Share PO →'}}
async function vendorUpdate(s){const p=products.find(x=>String(x.sku)===decodeURIComponent(s));if(!p)return;const q=prompt('Confirmed quantity:',p.confirmedQuantity||p.quantity||'');if(q===null)return;const d=prompt('Production days:',p.productionDays||'');if(d===null)return;const r=prompt('Vendor remarks:',p.vendorRemarks||'');if(r===null)return;const x=await api({action:'setVendorUpdate',token:token(),sku:p.sku,confirmedQuantity:q,productionDays:d,vendorRemarks:r});toast(x?.message||'Saved');if(x?.success)loadVendor()}
async function editProduct(s){const p=products.find(x=>String(x.sku)===decodeURIComponent(s));if(!p)return;const status=prompt('Admin Panel Status:',p.status||'');if(status===null)return;const vendor=prompt('Vendor:',p.vendor||'');if(vendor===null)return;const qty=prompt('Quantity:',p.quantity||'');if(qty===null)return;const remarks=prompt('Remarks:',p.remarks||'');if(remarks===null)return;const image=prompt('Image URL:',p.image||'');if(image===null)return;const r=await api({action:'saveProduct',token:token(),sku:p.sku,status,vendor,quantity:qty,remarks,image});toast(r?.message||'Saved');if(r?.success)loadAdmin()}
function bindEvents(){setupNavigation();$('vendorRole')?.addEventListener('click',()=>{loginRole='vendor';$('vendorRole').classList.add('active');$('adminRole').classList.remove('active')});$('adminRole')?.addEventListener('click',()=>{loginRole='admin';$('adminRole').classList.add('active');$('vendorRole').classList.remove('active')});$('loginBtn')?.addEventListener('click',login);$('loginPassword')?.addEventListener('keydown',e=>e.key==='Enter'&&login());$('logout')?.addEventListener('click',logout);$('vendorRefresh')?.addEventListener('click',loadVendor);$('vendorSearch')?.addEventListener('input',drawVendor);$('vendorSort')?.addEventListener('change',drawVendor);$('vendorPdf')?.addEventListener('click',()=>pdf(selectedRows(),'Selected Vendor Products'));$('vendorCsv')?.addEventListener('click',()=>{const r=selectedRows();if(r.length)csv([['SKU','Product','Supplier','Vendor','Cost','Qty','Status'],...r.map(p=>[p.sku,p.productName,p.supplier,p.vendor,p.landingCost,p.quantity,p.status])],'vendor-products.csv')});$('adminSearch')?.addEventListener('input',drawAdminProducts);$('adminVendorFilter')?.addEventListener('change',drawAdminProducts);$('adminStatusFilter')?.addEventListener('change',drawAdminProducts);$('adminSelectAll')?.addEventListener('click',selectAll);$('adminClearSelection')?.addEventListener('click',clearSelection);$('adminPdf')?.addEventListener('click',()=>pdf(selectedRows(),'Selected Products'));$('adminCsv')?.addEventListener('click',()=>{const r=selectedRows();if(r.length)csv([['SKU','Product','Supplier','Vendor','Cost','Qty','Status'],...r.map(p=>[p.sku,p.productName,p.supplier,p.vendor,p.landingCost,p.quantity,p.status])],'products.csv')});$('saveVendor')?.addEventListener('click',saveVendor);$('poClose')?.addEventListener('click',()=>$('poModal')?.classList.add('hidden'));$('poAdd')?.addEventListener('click',addPOSku);$('poSku')?.addEventListener('keydown',e=>e.key==='Enter'&&addPOSku());$('poCreate')?.addEventListener('click',createPO);$('poPdf')?.addEventListener('click',()=>pdf(poItems,'Purchase Order Preview'));document.addEventListener('change',e=>{if(e.target.matches('.selectProduct')){const s=String(e.target.dataset.sku);e.target.checked?selected.add(s):selected.delete(s)}})}
function boot(){bindEvents();const s=session();if(s?.token)openPortal(s)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();