const API='https://script.google.com/macros/s/AKfycbxc49T5iqv7V5XvZZciOyaW6a4_CGhjy6hjuxVwHehE8bOX8SGlTL-RJnbC4xpafWWx/exec';
const $=id=>document.getElementById(id), hide=id=>$(id)?.classList.add('hidden'), show=id=>$(id)?.classList.remove('hidden');
let products=[],lastUpdated='',busy=false;
function jsonp(params){return new Promise((resolve,reject)=>{const cb='mb_'+Date.now()+'_'+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const timer=setTimeout(()=>finish(reject,new Error('Website Listing gateway timed out.')),30000);function finish(fn,v){if(done)return;done=true;clearTimeout(timer);delete window[cb];s.remove();fn(v)}window[cb]=v=>finish(resolve,v);s.onerror=()=>finish(reject,new Error('Website Listing gateway is unavailable. Check the Apps Script deployment.'));s.async=true;s.src=API+'?'+new URLSearchParams({...params,callback:cb,_:Date.now()});document.head.appendChild(s)})}
function setConnection(state,text){const b=$('connectionBadge');if(!b)return;b.className='connection-badge '+state;b.innerHTML='<i></i> '+text}
function norm(p){return{...p,sku:String(p.sku||p.SKU||'').trim(),productName:String(p.productName||p.name||p.product_name||'').trim(),supplier:String(p.supplier||p.supplierName||'').trim(),price:p.price??p.landingCost??p.landing_cost??'',quantity:p.quantity??'',remarks:p.remarks??'',productLink:cleanUrl(p.productLink||p.product_link||p.link||p.url||''),image:cleanUrl(p.image||p.imageUrl||p.image_url||'')};}
function cleanUrl(v){let x=String(v||'').trim().replace(/\\u0026/g,'&').replace(/&amp;/g,'&');return/^https?:\/\//i.test(x)?x:''}
function isActive(p){const vals=[p.active,p.isActive,p.enabled,p.status,p.Status,p.productStatus,p.product_status];if(vals.every(v=>v===undefined||v===null||v===''))return true;return vals.some(v=>{if(v===undefined||v===null||v==='')return false;const x=String(v).trim().toLowerCase();return ['active','enabled','true','yes','1','live','published'].includes(x)})}
async function load(){if(busy)return;busy=true;setConnection('sync','SYNCING');$('catalogStatus').textContent='Fetching active products from Website Listing…';show('loading');hide('error');try{const r=await jsonp({action:'data'});if(!r)throw Error('Empty response from Website Listing.');if(r.success===false)throw Error(r.message||'Website Listing rejected the request.');const raw=Array.isArray(r.data)?r.data:(Array.isArray(r.products)?r.products:[]);products=raw.map(norm).filter(p=>(p.sku||p.productName)&&isActive(p));lastUpdated=r.updated||new Date().toISOString();render();updateMetrics();hide('loading');setConnection('online','LIVE');$('metricStatus').textContent='LIVE';$('metricStatusSub').textContent='Website Listing';$('catalogStatus').textContent=`${products.length.toLocaleString()} active products · synced ${new Date(lastUpdated).toLocaleString()}`}catch(e){hide('loading');show('error');$('error').textContent=e.message||'Unable to load Website Listing.';setConnection('error','OFFLINE');$('metricStatus').textContent='ERROR';$('metricStatusSub').textContent='Gateway unavailable';$('catalogStatus').textContent='Could not load the Website Listing master.'}finally{busy=false}}
function filtered(){const q=String($('searchInput')?.value||'').trim().toLowerCase(),sort=$('sortSelect')?.value||'default';let a=products.filter(p=>[p.sku,p.productName,p.supplier,p.price,p.remarks].join(' ').toLowerCase().includes(q));const v=x=>String(x??'').toLowerCase();if(sort==='name')a.sort((x,y)=>v(x.productName).localeCompare(v(y.productName)));else if(sort==='supplier')a.sort((x,y)=>v(x.supplier).localeCompare(v(y.supplier)));else if(sort==='price')a.sort((x,y)=>(parseFloat(x.price)||0)-(parseFloat(y.price)||0));else a.sort((x,y)=>v(x.sku).localeCompare(v(y.sku)));return a}
function render(){const box=$('products'),tpl=$('productTemplate');if(!box||!tpl)return;const list=filtered();const frag=document.createDocumentFragment();list.forEach(p=>{const n=tpl.content.cloneNode(true),wrap=n.querySelector('.image-wrap'),img=n.querySelector('.product-image'),a=n.querySelector('.product-link');n.querySelector('.sku').textContent=p.sku||'—';n.querySelector('.product-name').textContent=p.productName||'Product';n.querySelector('.supplier').textContent=p.supplier||'—';n.querySelector('.price').textContent=p.price===''?'—':p.price;n.querySelector('.quantity').textContent=p.sku||'—';n.querySelector('.remarks').textContent=p.remarks||'—';if(p.productLink){a.href=p.productLink}else{a.removeAttribute('href');a.textContent='No product link';a.style.opacity='.45'}if(p.image){img.src=p.image;img.onerror=()=>{wrap.classList.add('no-photo');img.removeAttribute('src')}}else{wrap.classList.add('no-photo')}frag.appendChild(n)});box.replaceChildren(frag);$('empty').classList.toggle('hidden',list.length>0);$('catalogStatus').textContent=`${list.length.toLocaleString()} shown · ${products.length.toLocaleString()} active in master`}
function updateMetrics(){const suppliers=new Set(products.map(p=>p.supplier).filter(Boolean));$('metricSkus').textContent=products.length.toLocaleString();$('metricSuppliers').textContent=suppliers.size.toLocaleString();$('metricSync').textContent=lastUpdated?new Date(lastUpdated).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—'}
$('searchInput')?.addEventListener('input',render);$('sortSelect')?.addEventListener('change',render);$('refreshBtn')?.addEventListener('click',load);document.addEventListener('DOMContentLoaded',load);