const API='https://script.google.com/macros/s/AKfycbwCGKZiV57bzmspcr5W2aVF5R7SpbwEqCs911boTjJbkPYvFEZJ-QNL0iD42qrxXfT9/exec';
const $=id=>document.getElementById(id);let products=[],vendors=[],pos=[],loginRole='vendor',selected=new Set(),poItems=[];
const session=()=>{try{return JSON.parse(localStorage.getItem('mb_vendor_session')||'null')}catch(e){return null}};const token=()=>session()?.token||'';
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function api(p){return new Promise((ok,no)=>{const cb='mb_'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const finish=(f,v)=>{if(done)return;done=true;clearTimeout(t);delete window[cb];s.remove();f(v)};const t=setTimeout(()=>finish(no,Error('Gateway timeout')),30000);window[cb]=v=>finish(ok,v);s.onerror=()=>finish(no,Error('Gateway unavailable'));s.async=true;s.src=API+'?'+new URLSearchParams({...p,callback:cb,_:Date.now()});document.head.appendChild(s)})}
function toast(m){const t=$('toast');if(!t)return;t.textContent=m;t.classList.remove('hidden');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.add('hidden'),3000)}
function setConn(x){const b=$('connection');b.textContent=x;b.className='status '+(x==='LIVE'?'live':'')}
function csv(rows,name){const q=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const s=rows.map(r=>r.map(q).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s],{type:'text/csv'}));a.download=name;a.click()}
function active(p){return String(p.status||'').trim().toLowerCase()==='active'}
function health(a){if(!a.length)return 0;return Math.round(a.filter(p=>p.productName&&p.sku&&p.productLink&&p.supplier&&p.image).length/a.length*100)}
function metric(a,b){return '<div class="metric"><span>'+esc(a)+'</span><b>'+esc(b)+'</b></div>'}
async function ensureImages(list,container){for(const p of list){if(p.image||!p.productLink)continue;try{const r=await api({action:'image',url:p.productLink,sku:p.sku});if(r?.image){p.image=r.image;const el=container?.querySelector('[data-sku="'+CSS.escape(String(p.sku))+'"]');if(el&&el.tagName==='IMG')el.src=r.image;else if(el)el.outerHTML='<img loading="lazy" data-sku="'+esc(p.sku)+'" src="'+esc(r.image)+'">'}}catch(e){}}}
function login(){const id=$('loginId').value.trim(),password=$('loginPassword').value;if(!id||!password){$('loginMsg').textContent='Enter ID and password.';return}const b=$('loginBtn');b.disabled=true;api({action:'login',role:loginRole,id,password}).then(r=>{if(!r?.success)throw Error(r?.message||'Login failed');localStorage.setItem('mb_vendor_session',JSON.stringify(r));openPortal(r)}).catch(e=>$('loginMsg').textContent=e.message).finally(()=>b.disabled=false)}
function openPortal(r){$('loginPanel').classList.add('hidden');$('portal').classList.remove('hidden');$('logout').classList.remove('hidden');$('welcome').textContent=r.role==='admin'?'Administrator Dashboard':'Welcome, '+r.name;$('vendorIdentity').textContent=r.role==='admin'?'MASTER access • products • vendors • purchase orders':'Vendor account • '+r.id;setConn('LIVE');r.role==='admin'?showAdmin():showVendor()}
async function logout(){try{await api({action:'logout',token:token()})}catch(e){}localStorage.removeItem('mb_vendor_session');location.reload()}
function showVendor(){$('vendorView').classList.remove('hidden');$('adminView').classList.add('hidden');loadVendor()};function showAdmin(){$('adminView').classList.remove('hidden');$('vendorView').classList.add('hidden');loadAdminProducts();loadVendors()}
async function loadVendor(){try{const r=await api({action:'vendorData',token:token()});if(!r?.success)throw Error(r?.message||'Session expired');products=(r.products||[]).filter(active);selected.clear();drawVendor();const po=await api({action:'vendorPurchaseOrders',token:token()});pos=po?.purchaseOrders||[];drawPO('vendorPO',pos);ensureImages(products,$('vendorProducts'))}catch(e){$('vendorProducts').innerHTML='<div class="state danger">'+esc(e.message)+'</div>'}}
function drawVendor(){const q=($('vendorSearch').value||'').toLowerCase(),sort=$('vendorSort').value;let a=products.filter(p=>[p.sku,p.productName,p.supplier,p.price,p.remarks].join(' ').toLowerCase().includes(q));const v=x=>String(x??'').toLowerCase();if(sort==='name')a.sort((x,y)=>v(x.productName).localeCompare(v(y.productName)));if(sort==='supplier')a.sort((x,y)=>v(x.supplier).localeCompare(v(y.supplier)));if(sort==='price')a.sort((x,y)=>(parseFloat(x.price)||0)-(parseFloat(y.price)||0));if(sort==='sku')a.sort((x,y)=>v(x.sku).localeCompare(v(y.sku)));$('vendorStats').innerHTML=metric('ASSIGNED PRODUCTS',products.length)+metric('VISIBLE RESULTS',a.length)+metric('LISTING HEALTH',health(products)+'%')+metric('WITH IMAGES',products.filter(p=>p.image).length)+metric('ACCESS','VENDOR ONLY');$('vendorProducts').innerHTML=a.length?a.map(p=>card(p,true)).join(''):'<div class="state">No active assigned products match.</div>';ensureImages(a,$('vendorProducts'))}
function card(p,vendor){const checked=selected.has(String(p.sku));return '<article class="card"><div class="photo">'+(p.image?'<img loading="lazy" data-sku="'+esc(p.sku)+'" src="'+esc(p.image)+'" onerror="this.style.display=\'none\';this.parentElement.innerHTML=\'<span class=loading>IMAGE UNAVAILABLE</span>\'">':'<span class="loading" data-sku="'+esc(p.sku)+'">LOADING IMAGE…</span>')+'</div><div class="body"><div class="actions"><label><input class="check selectProduct" data-sku="'+esc(p.sku)+'" type="checkbox" '+(checked?'checked':'')+'> Select</label><span class="pill ok">ACTIVE</span></div><div class="sku">'+esc(p.sku)+'</div><div class="name">'+esc(p.productName)+'</div><div class="meta"><div><small>SUPPLIER</small><b>'+esc(p.supplier||'—')+'</b></div><div><small>VENDOR</small><b>'+esc(p.vendor||'—')+'</b></div><div><small>LANDING COST</small><b>'+esc(p.landingCost||p.price||'—')+'</b></div><div><small>QUANTITY</small><b>'+esc(p.quantity||'—')+'</b></div><div><small>PRODUCTION DAYS</small><b>'+esc(p.productionDays||'—')+'</b></div><div><small>STATUS</small><b>'+esc(p.status||'—')+'</b></div></div><div class="actions">'+(p.productLink?'<a class="btn" target="_blank" href="'+esc(p.productLink)+'">Source ↗</a>':'')+(vendor?'<button class="btn" onclick="vendorUpdate(\''+encodeURIComponent(p.sku)+'\')">Update</button>':'<button class="btn" onclick="assignVendor(\''+encodeURIComponent(p.sku)+'\')">Assign Vendor</button>')+'</div></div></article>'}
async function vendorUpdate(s){const sku=decodeURIComponent(s),p=products.find(x=>x.sku===sku);if(!p)return;const q=prompt('Confirmed quantity:',p.confirmedQuantity||p.quantity||'');if(q===null)return;const d=prompt('Production days:',p.productionDays||'');if(d===null)return;const r=prompt('Vendor remarks:',p.vendorRemarks||p.remarks||'');if(r===null)return;const x=await api({action:'setVendorUpdate',token:token(),sku,confirmedQuantity:q,productionDays:d,vendorRemarks:r});toast(x?.message||'Saved');if(x?.success)loadVendor()}
function drawPO(id,a){const b=$(id);if(!a.length){b.innerHTML='<div class="state">No purchase orders.</div>';return}b.innerHTML='<table class="table"><thead><tr><th>PO</th><th>Vendor</th><th>SKU</th><th>Product</th><th>Qty</th><th>Status</th></tr></thead><tbody>'+a.map(x=>'<tr><td>'+esc(x.poId)+'</td><td>'+esc(x.vendorName||'')+'</td><td>'+esc(x.sku)+'</td><td>'+esc(x.productName)+'</td><td>'+esc(x.quantity)+'</td><td>'+esc(x.status)+'</td></tr>').join('')+'</tbody></table>'}
async function loadAdminProducts(){try{const r=await api({action:'adminProducts',token:token()});if(!r?.success)throw Error(r?.message||'Session expired');products=r.products||[];drawAdminStats();drawAdminProducts();ensureImages(products.filter(active),$('adminProductList'))}catch(e){$('adminProductList').innerHTML='<div class="state danger">'+esc(e.message)+'</div>'}}
function drawAdminStats(){const all=products,act=all.filter(active),img=act.filter(p=>p.image).length;$('adminStats').innerHTML=metric('TOTAL PRODUCTS',all.length)+metric('ACTIVE LISTINGS',act.length)+metric('INACTIVE',all.filter(p=>!active(p)).length)+metric('LISTING HEALTH',health(act)+'%')+metric('IMAGES',img+'/'+act.length)}
function drawAdminProducts(){const q=($('adminSearch').value||'').toLowerCase(),vf=$('adminVendorFilter').value,sf=$('adminStatusFilter').value.toLowerCase();let a=products.filter(p=>[p.sku,p.productName,p.supplier,p.vendor,p.price].join(' ').toLowerCase().includes(q));if(sf)a=a.filter(p=>String(p.status||'').toLowerCase()===sf);if(vf)a=a.filter(p=>String(p.vendor||'').toLowerCase()===vf.toLowerCase());$('adminProductList').innerHTML=a.length?a.map(p=>card(p,false)).join(''):'<div class="state">No matching products.</div>';populateVendorFilter();ensureImages(a,$('adminProductList'))}
function populateVendorFilter(){const s=$('adminVendorFilter'),c=s.value;s.innerHTML='<option value="">All vendors</option>'+vendors.map(v=>'<option value="'+esc(v.name)+'">'+esc(v.name)+'</option>').join('');s.value=c}
async function assignVendor(s){const sku=decodeURIComponent(s);if(!vendors.length)await loadVendors();const name=prompt('Select Vendor from Listing Master:\n\n'+vendors.map(v=>v.name).join('\n'));if(name===null)return;const v=vendors.find(x=>x.name.toLowerCase()===name.trim().toLowerCase());if(!v){toast('Vendor not found.');return}const r=await api({action:'setProductVendor',token:token(),sku,vendorId:v.id,vendorName:v.name});toast(r?.message||'Saved');if(r?.success)loadAdminProducts()}
async function loadVendors(){const r=await api({action:'adminVendors',token:token()});if(r?.success)vendors=r.vendors||[];await mergeListingMasterVendors();populateVendorFilter();$('vendorList').innerHTML=vendors.length?'<table class="table"><tr><th>Vendor</th><th>Portal Account</th><th>ID</th><th>Enabled</th></tr>'+vendors.map(v=>'<tr><td>'+esc(v.name)+'</td><td>'+esc(v.masterOnly?'Not created':'Portal account')+'</td><td>'+esc(v.id||'—')+'</td><td>'+esc(v.enabled??true)+'</td></tr>').join('')+'</table>':'<div class="state">No vendors found in Listing Master.</div>'}
async function mergeListingMasterVendors(){try{const r=await api({action:'data'});if(!r?.success)return;const map={};(r.data||[]).forEach(p=>{const n=String(p.vendor||p.vendorName||'').trim();if(n)map[n.toLowerCase()]=n});const existing={};vendors.forEach(v=>{if(v.name)existing[String(v.name).toLowerCase()]=v});Object.values(map).forEach(name=>{const k=name.toLowerCase();if(!existing[k])vendors.push({id:'master-'+k.replace(/[^a-z0-9]+/g,'-'),name,enabled:true,masterOnly:true})});vendors.sort((a,b)=>a.name.localeCompare(b.name))}catch(e){}}
async function saveVendor(){const r=await api({action:'saveVendor',token:token(),id:$('newVendorId').value.trim(),name:$('newVendorName').value.trim(),password:$('newVendorPassword').value,enabled:true});toast(r?.message||'Saved');if(r?.success){$('newVendorId').value='';$('newVendorName').value='';$('newVendorPassword').value='';loadVendors()}}
async function loadPO(){const r=await api({action:'purchaseOrders',token:token()});pos=r?.purchaseOrders||[];drawPO('adminPO',pos)}
function openPO(){loadVendors().then(()=>{$('poVendor').innerHTML='<option value="">Select vendor</option>'+vendors.map(v=>'<option value="'+esc(v.id)+'">'+esc(v.name)+(v.masterOnly?' — account needed':'')+'</option>').join('');poItems=[];renderPOItems();$('poModal').classList.remove('hidden')})}
function renderPOItems(){$('poItems').innerHTML=poItems.length?poItems.map((x,i)=>'<div class="poRow"><div><b>'+esc(x.sku)+'</b> — '+esc(x.productName)+'<div class="sub">'+esc(x.supplier||'')+' • Cost '+esc(x.landingCost||x.price||'')+'</div></div><input class="input" type="number" min="1" value="'+esc(x.quantity||1)+'" onchange="poItems['+i+'].quantity=this.value"><button class="btn dangerBtn" onclick="poItems.splice('+i+',1);renderPOItems()">×</button></div>').join(''):'<div class="state">Add one or more SKU products.</div>'}
async function addPOItem(){const sku=$('poSku').value.trim();if(!sku)return;const r=await api({action:'purchaseLookup',token:token(),sku});if(!r?.success){$('poLookup').textContent=r?.message||'SKU not found';return}if(poItems.some(x=>x.sku===r.product.sku)){toast('SKU already added');return}poItems.push({...r.product,quantity:1});$('poSku').value='';$('poLookup').textContent='';renderPOItems()}
async function createPO(){const vid=$('poVendor').value;if(!vid||!poItems.length){toast('Select vendor and add products.');return}const v=vendors.find(x=>x.id===vid);if(!v||v.masterOnly){toast('This Listing Master vendor has no portal account. Create the portal account first, then create the PO.');return}const items=poItems.map(x=>({sku:x.sku,quantity:x.quantity||1,remarks:x.remarks||''}));const r=await api({action:'savePurchaseOrder',token:token(),vendorId:v.id,vendorName:v.name,items:JSON.stringify(items)});if(r?.success){toast('PO created: '+r.poId);$('poModal').classList.add('hidden');loadPO()}else toast(r?.message||'Failed to create PO')}
function tab(x){['adminProductsSection','adminVendorsSection','adminPOSection'].forEach(id=>$(id).classList.add('hidden'));$(x).classList.remove('hidden');if(x==='adminProductsSection')loadAdminProducts();if(x==='adminVendorsSection')loadVendors();if(x==='adminPOSection')loadPO()}
function selectedRows(){return products.filter(p=>selected.has(String(p.sku)))}
function pdf(rows,title){if(!rows.length){toast('Select at least one product.');return}const w=window.open('','_blank');if(!w){toast('Allow pop-ups to export PDF.');return}const body=rows.map(p=>'<div class="item"><div class="pic">'+(p.image?'<img src="'+esc(p.image)+'">':'')+'</div><div><h2>'+esc(p.productName)+'</h2><p><b>SKU:</b> '+esc(p.sku)+' &nbsp; <b>Supplier:</b> '+esc(p.supplier)+'</p><p><b>Vendor:</b> '+esc(p.vendor||'—')+' &nbsp; <b>Landing Cost:</b> '+esc(p.landingCost||p.price||'—')+'</p><p><b>Quantity:</b> '+esc(p.quantity||'—')+' &nbsp; <b>Status:</b> '+esc(p.status||'—')+'</p><p><b>Link:</b> '+esc(p.productLink||'—')+'</p></div></div>').join('');w.document.write('<!doctype html><html><head><title>'+esc(title)+'</title><style>body{font:12px Arial;color:#102d2d;margin:30px}h1{color:#16e0bd;border-bottom:4px solid #b7f34a;padding-bottom:10px}.item{display:grid;grid-template-columns:150px 1fr;gap:18px;border-bottom:1px solid #ddd;padding:18px 0;page-break-inside:avoid}.pic{height:120px;border:1px solid #ddd;display:flex;align-items:center;justify-content:center}.pic img{max-width:100%;max-height:100%;object-fit:contain}h2{margin:0 0 8px;font-size:17px}</style></head><body><h1>MULTYBYTE — '+esc(title)+'</h1>'+body+'</body></html>');w.document.close();w.focus();setTimeout(()=>w.print(),700)}
function selectAll(){const q=($('adminSearch').value||'').toLowerCase(),vf=$('adminVendorFilter').value,sf=$('adminStatusFilter').value.toLowerCase();let a=products.filter(p=>[p.sku,p.productName,p.supplier,p.vendor,p.price].join(' ').toLowerCase().includes(q));if(sf)a=a.filter(p=>String(p.status||'').toLowerCase()===sf);if(vf)a=a.filter(p=>String(p.vendor||'').toLowerCase()===vf.toLowerCase());a.forEach(p=>selected.add(String(p.sku)));drawAdminProducts()}
$('loginBtn').onclick=login;$('logout').onclick=logout;$('vendorRole').onclick=()=>{loginRole='vendor';$('vendorRole').classList.add('primary');$('adminRole').classList.remove('primary')};$('adminRole').onclick=()=>{loginRole='admin';$('adminRole').classList.add('primary');$('vendorRole').classList.remove('primary')};$('vendorSearch').oninput=drawVendor;$('vendorSort').onchange=drawVendor;$('vendorRefresh').onclick=loadVendor;$('vendorPdf').onclick=()=>pdf(selectedRows(),'Selected Vendor Products');$('vendorCsv').onclick=()=>csv([['SKU','Product Name','Quantity','Confirmed Quantity','Supplier','Price','Production Days','Vendor Remarks','Product Link'],...products.map(p=>[p.sku,p.productName,p.quantity,p.confirmedQuantity,p.supplier,p.price,p.productionDays,p.vendorRemarks,p.productLink])],'vendor-products.csv');$('adminSearch').oninput=drawAdminProducts;$('adminVendorFilter').onchange=drawAdminProducts;$('adminStatusFilter').onchange=drawAdminProducts;$('adminSelectAll').onclick=selectAll;$('adminPdf').onclick=()=>pdf(selectedRows(),'Selected Multybyte Products');$('adminCsv').onclick=()=>csv([['SKU','Product Name','Supplier','Vendor','Landing Cost','Quantity','Status','Product Link'],...selectedRows().map(p=>[p.sku,p.productName,p.supplier,p.vendor,p.landingCost,p.quantity,p.status,p.productLink])],'selected-products.csv');$('adminProductsBtn').onclick=()=>tab('adminProductsSection');$('adminVendorsBtn').onclick=()=>tab('adminVendorsSection');$('adminPOBtn').onclick=()=>tab('adminPOSection');$('adminRefresh').onclick=()=>{if(!$('adminProductsSection').classList.contains('hidden'))loadAdminProducts();else if(!$('adminVendorsSection').classList.contains('hidden'))loadVendors();else loadPO()};$('saveVendor').onclick=saveVendor;$('createPO').onclick=openPO;$('poClose').onclick=()=>$('poModal').classList.add('hidden');$('poAdd').onclick=addPOItem;$('poSku').onkeydown=e=>{if(e.key==='Enter')addPOItem};$('poCreate').onclick=createPO;document.addEventListener('DOMContentLoaded',()=>{const s=session();if(s?.token)openPortal(s)})