/********************
 * MULTYBYTE WEBSITE LISTING PORTAL BACKEND
 * Product master: Website Listing
 ********************/
const MB_PORTAL={SPREADSHEET_ID:'1VsuPiZuuNucfhMidXUgIxHVBYMoTCL6urMOJkLK5_hU',MASTER_SHEET:'Website Listing',VENDOR_SHEET:'VENDORS',PO_SHEET:'PURCHASE_ORDERS',SESSION_TTL:21600,ADMIN_PROPERTY:'MB_ADMIN_HASH',ADMIN_ID_PROPERTY:'MB_ADMIN_ID',DEFAULT_ADMIN_ID:'admin',DEFAULT_ADMIN_HASH:'240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',VENDOR_HEADERS:['User ID','User Name','Sheet Name','Enabled','Password Hash'],VENDOR_PRODUCT_HEADERS:['SKU','Product Name','Quantity','Supplier','Product Link','Image','Landing Cost','Remarks','PO ID','Created At','Status'],PO_HEADERS:['PO ID','Created At','Created By','Vendor ID','Vendor Name','SKU','Product Name','Supplier','Landing Cost','Quantity','Remarks','Product Link','Image','Status']};
function doGet(e){try{const p=e&&e.parameter?e.parameter:{},a=String(p.action||'data').trim();let r;switch(a){case'data':r=publicSyncData_();break;case'image':r=publicProductImage_(p);break;case'login':r=login_(p);break;case'logout':r=logout_(p);break;case'vendorData':r=vendorData_(p);break;case'vendorPurchaseOrders':r=vendorPurchaseOrders_(p);break;case'adminVendors':case'vendors/list':r=adminVendors_(p);break;case'saveVendor':r=saveVendor_(p);break;case'adminProducts':case'adminProductMatrix':r=adminProducts_(p);break;case'saveProduct':case'adminSaveProduct':r=saveProduct_(p);break;case'deleteProduct':case'adminDeleteProduct':r=deleteProduct_(p);break;case'purchaseLookup':case'listingProduct':case'preparePOProduct':r=purchaseLookup_(p);break;case'searchListing':r=searchListing_(p);break;case'savePurchaseOrder':case'createPO':r=savePurchaseOrder_(p);break;case'purchaseOrders':case'listPurchaseOrders':r=purchaseOrders_(p);break;case'clearVendorPurchase':r=clearVendorPurchase_(p);break;case'portalStats':case'listingStats':r=portalStats_(p);break;case'setVendorUpdate':r=setVendorUpdate_(p);break;case'setVendorProduct':r=setVendorUpdate_(p);break;case'setProductVendor':r=setProductVendor_(p);break;case'setup':r=setupVendorPortal();break;default:r={success:false,message:'Unknown action: '+a,code:'UNKNOWN_ACTION'}}return output_(r,p.callback)}catch(err){return output_({success:false,message:String(err&&err.message||err),code:'SERVER_ERROR'},e&&e.parameter&&e.parameter.callback)}}
function doPost(e){return doGet(e)}
function setupVendorPortal(){const ss=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID);if(!ss.getSheetByName(MB_PORTAL.MASTER_SHEET))throw Error('Website Listing sheet not found.');ensureSheet_(ss,MB_PORTAL.VENDOR_SHEET,MB_PORTAL.VENDOR_HEADERS);ensureSheet_(ss,MB_PORTAL.PO_SHEET,MB_PORTAL.PO_HEADERS);ensureAdmin_();return{success:true,message:'Website Listing portal setup complete.'}}
function ensureSheet_(ss,n,h){let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(s.getLastRow()===0)s.getRange(1,1,1,h.length).setValues([h]);s.setFrozenRows(1);return s}
function ensureAdmin_(){const p=PropertiesService.getScriptProperties();if(!p.getProperty(MB_PORTAL.ADMIN_PROPERTY))p.setProperty(MB_PORTAL.ADMIN_PROPERTY,MB_PORTAL.DEFAULT_ADMIN_HASH);if(!p.getProperty(MB_PORTAL.ADMIN_ID_PROPERTY))p.setProperty(MB_PORTAL.ADMIN_ID_PROPERTY,MB_PORTAL.DEFAULT_ADMIN_ID)}
function setAdminPassword_(){const ui=SpreadsheetApp.getUi(),id=ui.prompt('Admin ID','Enter admin login ID:',ui.ButtonSet.OK_CANCEL);if(id.getSelectedButton()!==ui.Button.OK)return;const pw=ui.prompt('Admin Password','Enter new password:',ui.ButtonSet.OK_CANCEL);if(pw.getSelectedButton()!==ui.Button.OK||!pw.getResponseText())throw Error('Admin password was not set.');const p=PropertiesService.getScriptProperties();p.setProperty(MB_PORTAL.ADMIN_PROPERTY,hash_(pw.getResponseText()));p.setProperty(MB_PORTAL.ADMIN_ID_PROPERTY,id.getResponseText().trim()||'admin')}
function resetAdminPassword(){setAdminPassword_()}
function login_(p){const role=String(p.role||'vendor').toLowerCase(),id=String(p.id||'').trim(),pw=String(p.password||'');if(!id||!pw)return{success:false,message:'ID and password are required.'};if(role==='admin'){ensureAdmin_();const sp=PropertiesService.getScriptProperties();if(id!==(sp.getProperty(MB_PORTAL.ADMIN_ID_PROPERTY)||'admin')||hash_(pw)!==sp.getProperty(MB_PORTAL.ADMIN_PROPERTY))return{success:false,message:'Invalid admin ID or password.'};return{success:true,role:'admin',id,name:'Administrator',token:createSession_({role:'admin',id,name:'Administrator'})}}const v=findVendor_(id);if(!v||!v.enabled)return{success:false,message:'Vendor account is disabled or not found.'};if(hash_(pw)!==v.passwordHash)return{success:false,message:'Invalid vendor ID or password.'};return{success:true,role:'vendor',id:v.id,name:v.name,token:createSession_({role:'vendor',id:v.id,name:v.name,sheetName:v.sheetName})}}
function getMasterSheet_(){const s=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID).getSheetByName(MB_PORTAL.MASTER_SHEET);if(!s)throw Error('Website Listing sheet not found.');return s}
function masterHeaders_(){const s=getMasterSheet_(),h=s.getRange(1,1,1,s.getLastColumn()).getDisplayValues()[0];const ix={};h.forEach((x,i)=>{const k=String(x).trim().toLowerCase();if(k)ix[k]=i});const pick=names=>{for(const n of names){if(ix[n]!==undefined)return ix[n]}return -1};return{headers:h,name:pick(['product name','productname','name']),sku:pick(['sku','sku id','sku_id','skuid']),link:pick(['multybyte link','product link','productlink','link','url']),price:pick(['landing cost','landingcost','landing_cost','price','rmb']),supplier:pick(['supplier name','supplier','suppliername']),vendor:pick(['vendor name','vendor','vendorname']),status:pick(['admin panel status','status','product status','productstatus']),image:pick(['image','image url','imageurl','product image']),quantity:pick(['quantity','qty']),remarks:pick(['remarks','remark'])}}
function readMasterRows_(){const sh=getMasterSheet_(),m=masterHeaders_(),last=sh.getLastRow();return{sh,m,rows:last<2?[]:sh.getRange(2,1,last-1,sh.getLastColumn()).getDisplayValues()}}
function cell_(r,i){return i>=0?String(r[i]||'').trim():''}
function normalizeMasterProduct_(r,n,m){m=m||masterHeaders_();return{row:n,sku:cell_(r,m.sku),productName:cell_(r,m.name),productLink:cell_(r,m.link),price:cell_(r,m.price),landingCost:cell_(r,m.price),supplier:cell_(r,m.supplier),vendor:cell_(r,m.vendor),status:cell_(r,m.status),image:cell_(r,m.image),quantity:cell_(r,m.quantity),remarks:cell_(r,m.remarks),source:'Website Listing'}}
function publicSyncData_(){const x=readMasterRows_();return{success:true,source:'Website Listing',updated:new Date().toISOString(),data:x.rows.map((r,i)=>normalizeMasterProduct_(r,i+2,x.m)).filter(p=>p.sku||p.productName)}}
function publicProductImage_(p){const u=String(p.url||'').trim();if(!/^https?:\/\//i.test(u))return{success:false,image:'',message:'Invalid product URL.'};return{success:true,image:findImage_(u)||'',sku:String(p.sku||'').trim(),productLink:u}}
function adminProducts_(p){const s=getSession_(p.token,'admin');if(!s)return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const x=readMasterRows_(),data=x.rows.map((r,i)=>normalizeMasterProduct_(r,i+2,x.m)).filter(p=>p.sku||p.productName);touchSession_(p.token,s);return{success:true,source:'Website Listing',updated:new Date().toISOString(),total:data.length,data,products:data}}
function saveProduct_(p){const s=getSession_(p.token,'admin');if(!s)return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const x=readMasterRows_(),row=Number(p.row||0);if(row<2||row>x.sh.getLastRow())return{success:false,message:'A valid Website Listing row is required.'};const v=x.sh.getRange(row,1,1,x.sh.getLastColumn()).getValues()[0],set=(i,val)=>{if(i>=0&&val!==undefined)v[i]=val};set(x.m.sku,p.sku);set(x.m.name,p.productName);set(x.m.link,p.productLink);set(x.m.price,p.price);set(x.m.supplier,p.supplier);set(x.m.vendor,p.vendor);set(x.m.image,p.image);set(x.m.quantity,p.quantity);set(x.m.remarks,p.remarks);if(x.m.status>=0&&p.status!==undefined)set(x.m.status,p.status);x.sh.getRange(row,1,1,v.length).setValues([v]);return{success:true,message:'Website Listing product updated.',product:normalizeMasterProduct_(x.sh.getRange(row,1,1,v.length).getDisplayValues()[0],row,x.m)}}
function deleteProduct_(p){const s=getSession_(p.token,'admin');if(!s)return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const sh=getMasterSheet_(),row=Number(p.row||0);if(row<2||row>sh.getLastRow())return{success:false,message:'Invalid Website Listing row.'};sh.deleteRow(row);return{success:true,message:'Website Listing product removed.'}}
function adminVendors_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const sh=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID).getSheetByName(MB_PORTAL.VENDOR_SHEET);if(!sh||sh.getLastRow()<2)return{success:true,vendors:[]};return{success:true,vendors:sh.getRange(2,1,sh.getLastRow()-1,5).getDisplayValues().filter(r=>r[0]).map(r=>({id:r[0],name:r[1],sheetName:r[2],enabled:String(r[3]).toLowerCase()==='true'}))}}
function saveVendor_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const id=String(p.id||'').trim(),name=String(p.name||'').trim(),pw=String(p.password||''),enabled=p.enabled===undefined?true:String(p.enabled).toLowerCase()==='true';if(!id||!name)return{success:false,message:'User ID and vendor name are required.'};const ss=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),sh=ensureSheet_(ss,MB_PORTAL.VENDOR_SHEET,MB_PORTAL.VENDOR_HEADERS),rows=sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1,5).getValues():[];let row=0,oldHash='',oldSheet='';rows.forEach((r,i)=>{if(String(r[0]).trim()===id){row=i+2;oldHash=String(r[4]||'');oldSheet=String(r[2]||'')}});const sheetName=oldSheet||uniqueVendorSheetName_(ss,name,id);ensureVendorSheet_(ss,sheetName);if(!row){if(!pw)return{success:false,message:'Password is required for a new vendor.'};sh.appendRow([id,name,sheetName,enabled,hash_(pw)])}else{if(pw)oldHash=hash_(pw);sh.getRange(row,1,1,5).setValues([[id,name,sheetName,enabled,oldHash]])}return{success:true,message:row?'Vendor updated.':'Vendor created.',vendor:{id,name,sheetName,enabled}}}
function uniqueVendorSheetName_(ss,name,id){const base=(sanitizeSheetName_(name||id||'Vendor')||'Vendor').slice(0,95);let c=base,n=2;while(ss.getSheetByName(c))c=(base+' '+n++).slice(0,100);return c}
function sanitizeSheetName_(s){return String(s).replace(/[\\\/\?\*\[\]\:]/g,' ').replace(/^'+|'+$/g,'').trim().slice(0,100)}
function ensureVendorSheet_(ss,n){return ensureSheet_(ss,n,MB_PORTAL.VENDOR_PRODUCT_HEADERS)}
function findVendor_(id){const sh=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID).getSheetByName(MB_PORTAL.VENDOR_SHEET);if(!sh||sh.getLastRow()<2)return null;for(const r of sh.getRange(2,1,sh.getLastRow()-1,5).getValues()){if(String(r[0]).trim()===String(id).trim())return{id:String(r[0]).trim(),name:String(r[1]),sheetName:String(r[2]),enabled:r[3]===true||String(r[3]).toLowerCase()==='true',passwordHash:String(r[4]||'')}}return null}
function vendorData_(p){const s=getSession_(p.token,'vendor');if(!s)return{success:false,message:'Vendor session expired.'};const sh=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID).getSheetByName(s.sheetName);if(!sh)return{success:false,message:'Assigned vendor workspace no longer exists.'};const data=readVendorSheet_(sh);return{success:true,vendorId:s.id,vendorName:s.name,sheetName:s.sheetName,updated:new Date().toISOString(),data,products:data}}
function readVendorSheet_(sh){if(sh.getLastRow()<2)return[];const width=Math.max(11,Math.min(sh.getLastColumn(),MB_PORTAL.VENDOR_PRODUCT_HEADERS.length));return sh.getRange(2,1,sh.getLastRow()-1,width).getDisplayValues().map(x=>({sku:x[0],productName:x[1],quantity:x[2],supplier:x[3],productLink:x[4],image:x[5],price:x[6],landingCost:x[6],remarks:x[7],poId:x[8],createdAt:x[9],status:x[10]})).filter(p=>p.sku||p.productName||p.productLink)}
function purchaseLookup_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const sku=String(p.sku||'').trim(),x=readMasterRows_();if(!sku)return{success:false,message:'Enter a SKU.'};for(let i=0;i<x.rows.length;i++){const q=normalizeMasterProduct_(x.rows[i],i+2,x.m);if(q.sku.toLowerCase()===sku.toLowerCase()){q.image=q.image||findImage_(q.productLink)||'';return{success:true,source:'Website Listing',product:q}}}return{success:false,message:'SKU not found in Website Listing.',code:'SKU_NOT_FOUND'}}
function searchListing_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const q=String(p.query||p.sku||'').trim().toLowerCase();if(!q)return{success:true,data:[],products:[]};const x=readMasterRows_(),data=[];for(let i=0;i<x.rows.length&&data.length<50;i++){const z=normalizeMasterProduct_(x.rows[i],i+2,x.m);if((z.sku+' '+z.productName+' '+z.supplier+' '+z.vendor).toLowerCase().includes(q))data.push(z)}return{success:true,source:'Website Listing',total:data.length,data,products:data}}
function savePurchaseOrder_(p){const s=getSession_(p.token,'admin');if(!s)return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};let items=[];try{items=p.items?JSON.parse(String(p.items)):null}catch(e){return{success:false,message:'Invalid PO items.'}}if(!Array.isArray(items)||!items.length){if(String(p.sku||'').trim())items=[{sku:p.sku,productName:p.productName,supplier:p.supplier,landingCost:p.landingCost||p.price,quantity:p.quantity,remarks:p.remarks,productLink:p.productLink,image:p.image}];else return{success:false,message:'At least one SKU is required.'}}const vendor=findVendor_(p.vendorId||p.id);if(!vendor||!items.length)return{success:false,message:'Select a valid vendor and at least one SKU.'};const x=readMasterRows_(),map={};x.rows.forEach((r,i)=>{const z=normalizeMasterProduct_(r,i+2,x.m);if(z.sku)map[z.sku.toLowerCase()]=z});const ss=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),vsh=ensureVendorSheet_(ss,vendor.sheetName),psh=ensureSheet_(ss,MB_PORTAL.PO_SHEET,MB_PORTAL.PO_HEADERS),now=new Date(),poId='PO-'+Utilities.formatDate(now,Session.getScriptTimeZone(),'yyyyMMdd-HHmmss')+'-'+Utilities.getUuid().slice(0,6).toUpperCase(),vr=[],pr=[];items.forEach(it=>{const z=map[String(it.sku||'').trim().toLowerCase()];if(!z)throw Error('SKU not found in Website Listing: '+it.sku);const img=String(it.image||z.image||findImage_(z.productLink)||''),qty=String(it.quantity||'').trim(),rem=String(it.remarks||'').trim();vr.push([z.sku,z.productName,qty,z.supplier,z.productLink,img,z.landingCost,rem,poId,now,'CREATED']);pr.push([poId,now,s.id,vendor.id,vendor.name,z.sku,z.productName,z.supplier,z.landingCost,qty,rem,z.productLink,img,'CREATED'])});vsh.getRange(vsh.getLastRow()+1,1,vr.length,MB_PORTAL.VENDOR_PRODUCT_HEADERS.length).setValues(vr);psh.getRange(psh.getLastRow()+1,1,pr.length,14).setValues(pr);return{success:true,message:vr.length+' purchase item'+(vr.length===1?'':'s')+' saved.',poId,vendor,items:vr.map(r=>({sku:r[0],productName:r[1],quantity:r[2],supplier:r[3],productLink:r[4],image:r[5],price:r[6],landingCost:r[6],remarks:r[7]})),savedAt:now.toISOString()}}
function purchaseOrders_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.'};const sh=ensureSheet_(SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),MB_PORTAL.PO_SHEET,MB_PORTAL.PO_HEADERS);if(sh.getLastRow()<2)return{success:true,data:[],purchaseOrders:[],total:0};const rows=sh.getRange(2,1,sh.getLastRow()-1,14).getDisplayValues().reverse(),data=rows.map(r=>({poId:r[0],createdAt:r[1],createdBy:r[2],vendorId:r[3],vendor:r[4],vendorName:r[4],sku:r[5],productName:r[6],supplier:r[7],price:r[8],landingCost:r[8],quantity:r[9],remarks:r[10],productLink:r[11],image:r[12],status:r[13]}));return{success:true,total:data.length,data,purchaseOrders:data}}
function vendorPurchaseOrders_(p){const s=getSession_(p.token,'vendor');if(!s)return{success:false,message:'Vendor session expired.'};const sh=ensureSheet_(SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),MB_PORTAL.PO_SHEET,MB_PORTAL.PO_HEADERS);if(sh.getLastRow()<2)return{success:true,data:[],purchaseOrders:[],total:0};const rows=sh.getRange(2,1,sh.getLastRow()-1,14).getDisplayValues().filter(r=>String(r[3]).toLowerCase()===String(s.id).toLowerCase()).reverse(),data=rows.map(r=>({poId:r[0],createdAt:r[1],vendor:r[4],vendorName:r[4],sku:r[5],productName:r[6],supplier:r[7],price:r[8],landingCost:r[8],quantity:r[9],remarks:r[10],productLink:r[11],image:r[12],status:r[13]}));return{success:true,total:data.length,data,purchaseOrders:data}}
function clearVendorPurchase_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.'};const v=findVendor_(p.vendorId);if(!v)return{success:false,message:'Vendor account not found.'};const sh=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID).getSheetByName(v.sheetName);if(sh&&sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,Math.min(sh.getLastColumn(),MB_PORTAL.VENDOR_PRODUCT_HEADERS.length)).clearContent();return{success:true,message:'Vendor purchase workspace cleared.'}}
function setVendorUpdate_(p){const s=getSession_(p.token,'vendor');if(!s)return{success:false,message:'Vendor session expired.'};const sku=String(p.sku||'').trim();const sh=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID).getSheetByName(s.sheetName);if(!sh)return{success:false,message:'Vendor workspace not found.'};const rows=sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1,MB_PORTAL.VENDOR_PRODUCT_HEADERS.length).getValues():[];for(let i=0;i<rows.length;i++)if(String(rows[i][0]).trim().toLowerCase()===sku.toLowerCase()){if(p.quantity!==undefined)rows[i][2]=p.quantity;if(p.remarks!==undefined)rows[i][7]=p.remarks;sh.getRange(i+2,1,1,MB_PORTAL.VENDOR_PRODUCT_HEADERS.length).setValues([rows[i]]);return{success:true,message:'Vendor update saved.'}}return{success:false,message:'SKU not found in your assigned products.'}}
function setProductVendor_(p){const s=getSession_(p.token,'admin');if(!s)return{success:false,message:'Admin session expired.'};const x=readMasterRows_(),row=Number(p.row||0);if(row<2||row>x.sh.getLastRow()||x.m.vendor<0)return{success:false,message:'Invalid product/vendor field.'};x.sh.getRange(row,x.m.vendor+1).setValue(String(p.vendor||''));return{success:true,message:'Product vendor updated.'}}
function portalStats_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.'};const x=readMasterRows_(),ss=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),v=ss.getSheetByName(MB_PORTAL.VENDOR_SHEET),po=ss.getSheetByName(MB_PORTAL.PO_SHEET);return{success:true,source:'Website Listing',products:x.rows.filter(r=>cell_(r,x.m.sku)).length,vendors:v?Math.max(0,v.getLastRow()-1):0,purchaseOrders:po?Math.max(0,po.getLastRow()-1):0}}
function findImage_(url){if(!/^https?:\/\//i.test(String(url||'')))return'';const cache=CacheService.getScriptCache(),key='MBIMG_'+Utilities.base64EncodeWebSafe(String(url)).slice(0,180);const hit=cache.get(key);if(hit)return hit;try{const html=UrlFetchApp.fetch(url,{muteHttpExceptions:true,followRedirects:true,timeout:10000,headers:{'User-Agent':'Mozilla/5.0'}}).getContentText();const abs=(u)=>{u=decode_(u);try{return new URL(u,url).href}catch(e){return u}};const pats=[/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image["']/i,/<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"']+)/i,/<link[^>]+rel=["'][^"']*image_src[^"']*["'][^>]+href=["']([^"']+)/i,/<img[^>]+(?:data-src|data-lazy-src|data-original|src)=["']([^"']+)/i];for(const re of pats){const m=html.match(re);if(m){const u=abs(m[1]);if(/^https?:\/\//i.test(u)){cache.put(key,u,21600);return u}}}const ld=html.match(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/i);if(ld){try{const j=JSON.parse(ld[1]);const a=j.image||(Array.isArray(j['@graph'])&&j['@graph'].find(x=>x.image)?.image);const u=Array.isArray(a)?a[0]:a;if(u){const z=abs(u);if(/^https?:\/\//i.test(z)){cache.put(key,z,21600);return z}}}catch(e){}}}catch(e){}return''}
function decode_(s){return String(s||'').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\\u0026/g,'&').trim()}
function logout_(p){if(p&&p.token)CacheService.getScriptCache().remove('MBSESSION_'+p.token);return{success:true,message:'Session terminated.'}}
function output_(o,cb){const j=JSON.stringify(o);if(cb&&/^[A-Za-z_$][\w$\.]*$/.test(cb))return ContentService.createTextOutput(cb+'('+j+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(j).setMimeType(ContentService.MimeType.JSON)}
function hash_(s){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s),Utilities.Charset.UTF_8).map(x=>(x<0?x+256:x).toString(16).padStart(2,'0')).join('')}
function createSession_(d){const t=Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');CacheService.getScriptCache().put('MBSESSION_'+t,JSON.stringify(d),MB_PORTAL.SESSION_TTL);return t}
function getSession_(t,role){if(!t)return null;const raw=CacheService.getScriptCache().get('MBSESSION_'+t);if(!raw)return null;try{const s=JSON.parse(raw);return s.role===role?s:null}catch(e){return null}}
function touchSession_(t,s){CacheService.getScriptCache().put('MBSESSION_'+t,JSON.stringify(s),MB_PORTAL.SESSION_TTL)}
function onOpen(){SpreadsheetApp.getUi().createMenu('MULTYBYTE PORTAL').addItem('Setup / Repair Vendor Portal','setupVendorPortal').addItem('Reset Admin Password','resetAdminPassword').addToUi()}
