/* MULTYBYTE SAFE ENHANCEMENTS — image hydration, vendor fallback, PDF card export */
(function(){'use strict';
const API='https://script.google.com/macros/s/AKfycbwCGKZiV57bzmspcr5W2aVF5R7SpbwEqCs911boTjJbkPYvFEZJ-QNL0iD42qrxXfT9/exec';
const $=id=>document.getElementById(id);
const S=()=>{try{return JSON.parse(localStorage.getItem('mb_vendor_session')||'null')}catch(e){return null}};
const T=()=>S()?.token||'';
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function call(p,timeout=30000){return new Promise((res,rej)=>{let done=false,timer,sc,tryNo=0;const run=()=>{tryNo++;const cb='mb_enh_'+Date.now()+'_'+Math.random().toString(36).slice(2);const q=new URLSearchParams({...p,callback:cb,_enh:Date.now()});const clean=()=>{clearTimeout(timer);try{delete window[cb]}catch(e){}sc?.remove()};window[cb]=d=>{if(done)return;done=true;clean();res(d)};sc=document.createElement('script');sc.src=API+'?'+q.toString();sc.async=true;sc.onerror=()=>{clean();if(tryNo<3){setTimeout(run,500*tryNo)}else{done=true;rej(Error('Gateway unavailable'))}};document.head.appendChild(sc);timer=setTimeout(()=>{clean();if(tryNo<3){setTimeout(run,500*tryNo)}else{done=true;rej(Error('Gateway timeout'))}},timeout)};run()})}
function norm(p){p=p||{};return {sku:String(p.sku??p.SKU??p.SKU_ID??''),productName:p.productName||p.name||p['Product Name']||'',productLink:p.productLink||p.productURL||p.link||p['Multybyte Link']||'',image:p.image||p.imageUrl||p['Image']||'',supplier:p.supplier||p.supplierName||p['Supplier Name']||'',vendor:p.vendor||p.vendorName||p['Vendor Name']||'',price:p.price??p.landingCost??p['Landing Cost']??'',landingCost:p.landingCost??p.price??'',quantity:p.quantity??p.qty??'',remarks:p.remarks||p.remark||p['Remarks']||'',status:p.status||p.productStatus||p['Admin Panel Status']||'Active'}}
async function hydrateImages(list){list=Array.isArray(list)?list:[];const cache=JSON.parse(localStorage.getItem('mb_image_cache_v2')||'{}');let changed=false;const jobs=list.filter(p=>p&&p.sku&&p.productLink&&!p.image).slice();let i=0;async function worker(){while(i<jobs.length){const p=jobs[i++],k=p.sku;if(cache[k]){p.image=cache[k];continue}try{const r=await call({action:'image',url:p.productLink,sku:p.sku},18000);const u=r?.image||'';if(u){p.image=u;cache[k]=u;changed=true}}catch(e){}}}await Promise.all(Array.from({length:6},worker));if(changed)localStorage.setItem('mb_image_cache_v2',JSON.stringify(cache));return list}
async function refreshAdmin(){const [a,v,m]=await Promise.all([call({action:'adminProducts',token:T()}),call({action:'adminVendors',token:T()}),call({action:'data',token:T()})]);if(a?.success===false)throw Error(a.message);const products=(a?.products||a?.data||[]).map(norm);const master=(m?.data||m?.products||[]).map(norm);await hydrateImages(products);window.__MB_STATE_PRODUCTS=products;window.__MB_STATE_MASTER=master;window.__MB_STATE_VENDORS=(v?.vendors||[]);try{window.eval('products=window.__MB_STATE_PRODUCTS;masterProducts=window.__MB_STATE_MASTER;vendors=window.__MB_STATE_VENDORS;')}catch(e){}if(typeof drawAdminStats==='function')drawAdminStats();if(typeof drawAdminProducts==='function')drawAdminProducts();if(typeof drawDashboard==='function')drawDashboard();if(window.loadPOFixed)await window.loadPOFixed()}
async function refreshVendor(){const [r,p,m]=await Promise.all([call({action:'vendorData',token:T()}),call({action:'vendorPurchaseOrders',token:T()}),call({action:'data'})]);let products=(r?.products||r?.data||[]).map(norm);const master=(m?.data||m?.products||[]).map(norm);const s=S()||{};if(!products.length){products=master.filter(x=>{const a=String(x.vendor||'').trim().toLowerCase();return a&&(a===String(s.name||'').trim().toLowerCase()||a===String(s.id||'').trim().toLowerCase())})}await hydrateImages(products);const pos=p?.purchaseOrders||p?.data||[];window.__MB_STATE_PRODUCTS=products;window.__MB_STATE_POS=pos;try{window.eval('products=window.__MB_STATE_PRODUCTS;pos=window.__MB_STATE_POS;')}catch(e){}if(typeof drawVendor==='function')drawVendor();if(typeof drawPO==='function')drawPO('vendorPO',pos);if(typeof drawDashboard==='function')drawDashboard()}
function selectedProducts(){const checked=[...document.querySelectorAll('.selectProduct:checked')].map(x=>String(x.dataset.sku));const all=window.__MB_STATE_PRODUCTS||[];return (checked.length?all.filter(p=>checked.includes(String(p.sku))):all).map(norm)}
async function pdfCards(rows,title){rows=await hydrateImages(rows);const w=window.open('','_blank');if(!w)return;const blocks=rows.map(p=>{const img=p.image?'<img src="'+esc(p.image)+'">':'<div class="noimg">NO IMAGE</div>';return '<section class="item"><div class="pic">'+img+'</div><div class="info"><h2>'+esc(p.productName||'—')+'</h2><div class="sku">'+esc(p.sku||'—')+'</div><div class="grid"><div><small>QUANTITY</small><b>'+esc(p.quantity||'—')+'</b></div><div><small>SUPPLIER</small><b>'+esc(p.supplier||'—')+'</b></div><div><small>VENDOR</small><b>'+esc(p.vendor||'—')+'</b></div><div><small>PRICE</small><b>'+esc(p.price??p.landingCost??'—')+'</b></div></div><div class="remarks"><small>REMARKS</small><p>'+esc(p.remarks||'—')+'</p></div></div></section>'}).join('');w.document.write('<!doctype html><html><head><title>'+esc(title)+'</title><style>@page{size:A4;margin:12mm}body{font:12px Arial;color:#111;margin:0}.head{font-size:20px;font-weight:800;margin-bottom:14px;border-bottom:2px solid #16e0bd;padding-bottom:8px}.item{display:flex;gap:18px;border:1px solid #ccc;border-radius:8px;padding:12px;margin:0 0 14px;page-break-inside:avoid;min-height:145px}.pic{width:170px;min-width:170px;height:145px;display:flex;align-items:center;justify-content:center;background:#f5f5f5;border:1px solid #ddd}.pic img{max-width:100%;max-height:100%;object-fit:contain}.noimg{color:#999;font-size:10px}.info{flex:1}.info h2{font-size:16px;margin:0 0 4px}.sku{font-size:10px;color:#087f70;font-weight:700;margin-bottom:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.grid div{border:1px solid #eee;padding:6px}.grid small,.remarks small{display:block;font-size:8px;color:#777;font-weight:700}.grid b{font-size:10px}.remarks{margin-top:8px}.remarks p{margin:3px 0}.foot{font-size:9px;color:#777;margin-top:10px}@media print{.item{break-inside:avoid}}</style></head><body><div class="head">'+esc(title)+'</div>'+blocks+'<div class="foot">Multybyte • Website Listing source</div></body></html>');w.document.close();setTimeout(()=>{w.focus();w.print()},1000)}
function bind(){const ap=$('adminPdf');if(ap){const n=ap.cloneNode(true);ap.replaceWith(n);n.addEventListener('click',()=>pdfCards(selectedProducts(),'Selected Products'))}const vp=$('vendorPdf');if(vp){const n=vp.cloneNode(true);vp.replaceWith(n);n.addEventListener('click',()=>pdfCards(selectedProducts(),'Vendor Products'))}const pp=$('poPdf');if(pp){const n=pp.cloneNode(true);pp.replaceWith(n);n.addEventListener('click',()=>pdfCards((window.poItems||[]).map(norm),'Purchase Order'))}if($('adminPORefresh'))$('adminPORefresh').addEventListener('click',()=>window.loadPOFixed&&window.loadPOFixed());}
async function install(){window.__MB_ENHANCE_VERSION='image-vendor-pdf-v1';window.__MB_ENHANCE={hydrateImages,refreshAdmin,refreshVendor,pdfCards};const oldOpen=window.openPortal;window.openPortal=async r=>{if(typeof oldOpen==='function')oldOpen(r);try{if(r?.role==='admin')await refreshAdmin();else await refreshVendor()}catch(e){toastSafe(e.message)}};bind();const s=S();if(s){try{if(s.role==='admin')await refreshAdmin();else await refreshVendor()}catch(e){toastSafe('Data refresh failed: '+e.message)}}}
function toastSafe(x){if(typeof window.toast==='function')window.toast(x);else console.log(x)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
