/* MULTYBYTE PORTAL — GATEWAY PATCH */
(function(){'use strict';
const API='https://script.google.com/macros/s/AKfycbwCGKZiV57bzmcrW5aVF5R7SpbwEqCs911boTjJbkPYvFEZJ-QNL0iD42qrxXfT9/exec';
function gateway(p,timeout){timeout=timeout||30000;return new Promise((resolve,reject)=>{let n=0,done=false,sc,t;const go=()=>{n++;const cb='mbfix_'+Date.now()+'_'+Math.random().toString(36).slice(2);const q=new URLSearchParams({...p,callback:cb,_ts:Date.now(),_try:n});const clean=()=>{clearTimeout(t);try{delete window[cb]}catch(e){}if(sc)sc.remove()};const finish=(ok,v)=>{if(done)return;done=true;clean();ok?resolve(v):reject(v)};window[cb]=v=>finish(true,v);sc=document.createElement('script');sc.async=true;sc.src=API+'?'+q;sc.onload=()=>{};sc.onerror=()=>{if(n<4){clean();setTimeout(go,400*n)}else finish(false,new Error('Gateway unavailable'))};document.head.appendChild(sc);t=setTimeout(()=>{if(n<4){clean();setTimeout(go,300*n)}else finish(false,new Error('Gateway timeout'))},timeout)};go()})}
window.__MB_GATEWAY=gateway;
function norm(p){return typeof normalizeProduct==='function'?normalizeProduct(p):p}
function rows(r){return (r?.data||r?.products||[]).map(norm).filter(x=>x&&x.sku)}
async function safePO(){try{const r=await gateway({action:'purchaseOrders',token:token()});if(!r?.success)throw Error(r?.message||'Purchase orders failed');pos=r.purchaseOrders||r.data||[];if(typeof drawPO==='function')drawPO('adminPO',pos);if(typeof drawDashboard==='function')drawDashboard();return r}catch(e){toast('Purchase orders failed: '+e.message)}}
async function safeAdmin(){try{const [a,v,m]=await Promise.all([gateway({action:'adminProducts',token:token()}),gateway({action:'adminVendors',token:token()}),gateway({action:'data'})]);products=rows(a);masterProducts=rows(m);vendors=(v?.vendors||[]).map(x=>typeof normalizeVendor==='function'?normalizeVendor(x):x);if(typeof mergeMasterVendors==='function')mergeMasterVendors(m);if(typeof drawAdminStats==='function')drawAdminStats();if(typeof drawAdminProducts==='function')drawAdminProducts();if(typeof drawDashboard==='function')drawDashboard();await safePO()}catch(e){toast('Admin gateway failed: '+e.message)}}
async function safeVendors(){try{const r=await gateway({action:'adminVendors',token:token()});vendors=(r?.vendors||[]).map(x=>typeof normalizeVendor==='function'?normalizeVendor(x):x);const m=await gateway({action:'data'});if(typeof mergeMasterVendors==='function')mergeMasterVendors(m);if(typeof drawDashboard==='function')drawDashboard();if(typeof loadVendors==='function'&&!window.__mbVendorGuard){window.__mbVendorGuard=true;try{loadVendors()}finally{window.__mbVendorGuard=false}}}catch(e){toast('Vendors failed: '+e.message)}}
async function safeLookup(){const sku=document.getElementById('poSku')?.value.trim();if(!sku)return;try{const r=await gateway({action:'purchaseLookup',token:token(),sku});if(!r?.success)throw Error(r?.message||'SKU lookup failed');const p=norm(r.product);if(!p?.sku)throw Error('SKU not found in Website Listing');if(poItems.some(x=>String(x.sku).toLowerCase()===String(p.sku).toLowerCase()))throw Error('SKU already added.');poItems.push({...p,quantity:1});document.getElementById('poSku').value='';if(typeof renderPOItems==='function')renderPOItems();document.getElementById('poLookup').textContent='Added '+p.productName}catch(e){document.getElementById('poLookup').textContent=e.message;toast(e.message)}}
async function safeCreate(){const vs=typeof selectedPOVendors==='function'?selectedPOVendors():[];if(!vs.length)return toast('Select at least one vendor.');if(!poItems.length)return toast('Add at least one SKU.');const b=document.getElementById('poCreate');if(b)b.disabled=true;try{for(const v of vs){const r=await gateway({action:'savePurchaseOrder',token:token(),vendorId:v.id,vendorName:v.name,items:JSON.stringify(poItems.map(p=>({sku:p.sku,quantity:p.quantity,remarks:p.remarks||''})))});if(!r?.success)throw Error(r?.message||'Purchase order failed')}toast('Purchase order created successfully.');if(typeof closePO==='function')closePO();await safePO()}catch(e){toast('Purchase order failed: '+e.message)}finally{if(b)b.disabled=false}}
function install(){window.loadAdmin=safeAdmin;window.loadPO=safePO;window.loadVendors=safeVendors;window.addPOSku=safeLookup;window.createPO=safeCreate;window.__MB_API_READY=true;[['adminPORefresh',safePO],['poAdd',safeLookup],['poCreate',safeCreate]].forEach(([id,fn])=>{const x=document.getElementById(id);if(x)x.onclick=fn});setTimeout(()=>{document.querySelectorAll('.card').forEach(c=>{const cb=c.querySelector('.selectProduct');if(cb&&cb.dataset.sku&&!c.dataset.mbFix){c.dataset.mbFix='1';const p=rows({data:[findProduct(cb.dataset.sku)]})[0];if(p&&p.productLink&&!p.image)gateway({action:'image',url:p.productLink,sku:p.sku}).then(r=>{if(r?.image){p.image=r.image;const box=c.querySelector('.photo');if(box)box.innerHTML='<img loading="lazy" src="'+esc(r.image)+'">'}}).catch(()=>{})}})},500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();