/* MULTYBYTE PO VENDOR VISIBILITY HOTFIX
 * This file intentionally touches only PO vendor rendering.
 */
(function(){'use strict';
const $=id=>document.getElementById(id);
function s(){try{return JSON.parse(localStorage.getItem('mb_vendor_session')||'null')}catch(e){return null}}
function t(){return s()?.token||''}
function gw(p){return new Promise((resolve,reject)=>{const cb='mb_po_'+Date.now()+'_'+Math.random().toString(36).slice(2);const sc=document.createElement('script');const q=new URLSearchParams({...p,token:t(),callback:cb,_mbts:Date.now()});window[cb]=x=>{delete window[cb];sc.remove();resolve(x)};sc.onerror=()=>{delete window[cb];sc.remove();reject(Error('Gateway unavailable'))};sc.src='https://script.google.com/macros/s/AKfycbwCGKZiV57bzmspcr5W2aVF5R7SpbwEqCs911boTjJbkPYvFEZJ-QNL0iD42qrxXfT9/exec?'+q;document.head.appendChild(sc);setTimeout(()=>{if(window[cb]){delete window[cb];sc.remove();reject(Error('Gateway timeout'))}},25000)})}
function esc(x){return String(x??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function box(){return $('poVendors')||$('vendorList')||document.querySelector('#poModal .multiVendor')||document.querySelector('.modal .multiVendor')}
function normV(v){return {id:String(v.id||v.userId||v.userID||v.vendorId||v.vendorID||''),name:String(v.name||v.vendorName||v.vendor||v.userName||v['Vendor Name']||v['Supplier Name']||'').trim(),enabled:v.enabled!==false&&v.status!=='Disabled'}}
function normP(p){return {sku:String(p?.sku??p?.SKU??p?.SKU_ID??p?.['SKU']??'').trim(),productName:p?.productName||p?.name||p?.['Product Name']||'',vendor:p?.vendor||p?.vendorName||p?.['Vendor Name']||p?.supplier||p?.supplierName||p?.['Supplier Name']||'',remarks:p?.remarks||p?.['Remarks']||'',price:p?.price??p?.['Price']??p?.landingCost??''}}
async function render(){const b=box();if(!b)return;try{const vr=await gw({action:'adminVendors'});const mr=await gw({action:'data'});let vs=(Array.isArray(vr?.vendors)?vr.vendors:Array.isArray(vr?.data)?vr.data:Array.isArray(vr?.users)?vr.users:[]).map(normV).filter(v=>v.name&&v.enabled);const ps=(Array.isArray(mr?.products)?mr.products:Array.isArray(mr?.data)?mr.data:[]).map(normP);const seen=new Set(vs.map(v=>v.name.toLowerCase()));ps.forEach(p=>{if(p.vendor&&!seen.has(p.vendor.toLowerCase())){vs.push({id:'listing-'+p.vendor.toLowerCase().replace(/[^a-z0-9]+/g,'-'),name:p.vendor,enabled:true});seen.add(p.vendor.toLowerCase())}});window.__MB_STATE_VENDORS=vs;try{window.eval('vendors=window.__MB_STATE_VENDORS')}catch(e){}b.innerHTML=vs.length?vs.map(v=>'<label><input class="poVendorCheck" type="checkbox" value="'+esc(v.id)+'" data-name="'+esc(v.name)+'"><span><b>'+esc(v.name)+'</b></span></label>').join(''):'<div class="state">No vendors available.</div>'}catch(e){b.innerHTML='<div class="state">Unable to load vendors. Please retry.</div>'}}
async function sku(){const el=$('poSku'),v=el?.value.trim();if(!v)return;try{let r=await gw({action:'purchaseLookup',sku:v});let p=r?.success?normP(r.product||r.data):null;if(!p?.sku){r=await gw({action:'searchListing',query:v});const a=Array.isArray(r?.data)?r.data:Array.isArray(r?.products)?r.products:[];p=normP(a.find(x=>String(x?.sku??x?.SKU??x?.SKU_ID??x?.['SKU']??'').trim().toLowerCase()===v.toLowerCase()))}if(!p?.sku)throw Error('SKU not found in Website Listing');window.poItems=Array.isArray(window.poItems)?window.poItems:[];if(window.poItems.some(x=>String(x.sku).toLowerCase()===p.sku.toLowerCase()))throw Error('SKU already added');window.poItems.push({...p,quantity:1});try{window.eval('poItems=window.poItems')}catch(e){}el.value='';if(typeof renderPOItems==='function')renderPOItems();const target=p.vendor.toLowerCase();document.querySelectorAll('.poVendorCheck').forEach(c=>{if(String(c.dataset.name||'').toLowerCase()===target)c.checked=true})}catch(e){if(typeof window.toast==='function')window.toast(e.message);else console.error(e)}}
function open(){if(s()?.role!=='admin')return;window.poItems=[];try{window.eval('poItems=window.poItems')}catch(e){}const m=$('poModal')||document.querySelector('.modal');if(m)m.classList.remove('hidden');render();if(typeof renderPOItems==='function')renderPOItems()}
function install(){window.openPO=open;window.addPOSku=sku;const q=$('quickCreatePO');if(q){q.onclick=open}const a=$('poAdd');if(a){a.onclick=sku}const k=$('poSku');if(k)k.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();sku()}};document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const text=(b.textContent||'').trim().toLowerCase();if(text.includes('create purchase order')||text==='+ create po'){e.preventDefault();e.stopImmediatePropagation();open()}} ,true);setTimeout(()=>{if(!$('poVendors')&&!$('vendorList'))return;render()},800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
