/* LIVE GLOBAL CONTROLS — loaded after app.js + fix.js */
(function(){
  'use strict';
  const E=x=>typeof esc==='function'?esc(x):String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const T=m=>typeof toast==='function'?toast(m):alert(m);
  function remove(id){document.getElementById(id)?.remove()}
  function adminEditor(sku){
    const p=(typeof findLiveProduct==='function'?findLiveProduct(sku):null)||(()=>{try{return products.find(x=>String(x.sku)===String(decodeURIComponent(sku)))}catch(e){return null}})();
    if(!p||typeof session!=='function'||session()?.role!=='admin')return;
    remove('mbLiveEditor');
    const m=document.createElement('div');m.id='mbLiveEditor';m.className='modal';m.innerHTML=`<div class="modalBox" style="max-width:760px"><div class="sectionTitle"><div><div class="eyebrow">WEBSITE LISTING / EDIT</div><h2 style="margin:4px 0">Edit ${E(p.sku)}</h2></div><button class="btn" id="mbLEClose">Close</button></div><div class="notice">These editable fields are saved directly to the same Website Listing row. Source fields stay locked so the portal cannot accidentally overwrite the listing master.</div><div class="mbEditGrid" style="margin-top:14px"><div><small>SKU — LOCKED</small><input class="field" value="${E(p.sku)}" disabled></div><div><small>Product Name — LOCKED</small><input class="field" value="${E(p.productName)}" disabled></div><div><small>Supplier — LOCKED</small><input class="field" value="${E(p.supplier)}" disabled></div><div><small>Price — LOCKED</small><input class="field" value="${E(p.price??p.landingCost??'')}" disabled></div><div><small>Vendor — EDITABLE</small><input id="mbLEV" class="field" value="${E(p.vendor||'')}"></div><div><small>Status — EDITABLE</small><select id="mbLES" class="field"><option ${String(p.status).toLowerCase()==='active'?'selected':''}>Active</option><option ${String(p.status).toLowerCase()==='inactive'?'selected':''}>Inactive</option><option ${String(p.status).toLowerCase()==='pending'?'selected':''}>Pending</option></select></div><div><small>Quantity — EDITABLE</small><input id="mbLEQ" class="field" type="number" min="0" value="${E(p.quantity||'')}"></div><div><small>Image URL — EDITABLE</small><input id="mbLEI" class="field" value="${E(p.image||'')}"></div><div class="full"><small>Remarks — EDITABLE</small><textarea id="mbLER" class="field" rows="4">${E(p.remarks||'')}</textarea></div></div><div class="actions"><button id="mbLESave" class="btn primary">Save to Website Listing</button></div></div>`;
    document.body.appendChild(m);document.getElementById('mbLEClose').onclick=()=>m.remove();
    document.getElementById('mbLESave').onclick=async()=>{const b=document.getElementById('mbLESave');b.disabled=true;b.textContent='Saving…';try{const r=await api({action:'saveProduct',token:token(),row:p.row,sku:p.sku,status:document.getElementById('mbLES').value,vendor:document.getElementById('mbLEV').value,quantity:document.getElementById('mbLEQ').value,remarks:document.getElementById('mbLER').value,image:document.getElementById('mbLEI').value},20000);if(!r?.success)throw Error(r?.message||'Save failed');m.remove();T('Saved to Website Listing.');try{localStorage.removeItem('mb_listing_cache_v2')}catch(e){}await loadAdmin()}catch(e){T(e.message);b.disabled=false;b.textContent='Save to Website Listing'}};
  }
  function vendorEditor(sku){
    let p=null;try{p=products.find(x=>String(x.sku)===String(decodeURIComponent(sku)))}catch(e){}if(!p||typeof session!=='function'||session()?.role!=='vendor')return;
    remove('mbLiveVendorEditor');const text=String(p.remarks||''),dm=text.match(/Production Days:\s*([^\n]*)/i),rm=text.match(/Vendor Remarks:\s*([\s\S]*)/i);
    const m=document.createElement('div');m.id='mbLiveVendorEditor';m.className='modal';m.innerHTML=`<div class="modalBox" style="max-width:650px"><div class="sectionTitle"><div><div class="eyebrow">VENDOR UPDATE</div><h2 style="margin:4px 0">${E(p.sku)}</h2></div><button class="btn" id="mbLVC">Close</button></div><div class="notice">Confirmed quantity updates the Quantity column in your assigned vendor sheet. Production days and vendor remarks are stored in that row's Remarks field, so they remain after refresh.</div><div style="margin-top:14px"><small>Confirmed Quantity</small><input id="mbLVQ" class="field" type="number" min="0" value="${E(p.quantity||'')}"><small>Production Days</small><input id="mbLVD" class="field" type="number" min="0" value="${E(dm?dm[1].trim():'')}"><small>Vendor Remarks</small><textarea id="mbLVR" class="field" rows="4">${E(rm?rm[1].trim():text)}</textarea></div><button id="mbLVS" class="btn primary">Save Vendor Update</button></div>`;
    document.body.appendChild(m);document.getElementById('mbLVC').onclick=()=>m.remove();document.getElementById('mbLVS').onclick=async()=>{const b=document.getElementById('mbLVS');b.disabled=true;b.textContent='Saving…';try{const remarks='Production Days: '+document.getElementById('mbLVD').value+'\nVendor Remarks: '+document.getElementById('mbLVR').value;const r=await api({action:'setVendorUpdate',token:token(),sku:p.sku,quantity:document.getElementById('mbLVQ').value,remarks},20000);if(!r?.success)throw Error(r?.message||'Vendor update failed');m.remove();T('Vendor sheet updated.');await loadVendor()}catch(e){T(e.message);b.disabled=false;b.textContent='Save Vendor Update'}};
  }
  window.editProduct=adminEditor;
  window.vendorUpdate=vendorEditor;
})();
