/* MULTYBYTE PO FIX — vendor selection + reliable SKU lookup */
(function(){
'use strict';
const $=id=>document.getElementById(id);
const escSafe=x=>typeof window.esc==='function'?window.esc(x):String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normV=v=>typeof window.normalizeVendorSafe==='function'?window.normalizeVendorSafe(v):{id:v?.id||'',name:v?.name||v?.vendorName||'',enabled:v?.enabled!==false,masterOnly:!!v?.masterOnly};
const normP=p=>typeof window.normalizeProductSafe==='function'?window.normalizeProductSafe(p):(typeof window.normalizeProduct==='function'?window.normalizeProduct(p):p||{});
function currentVendors(){try{const a=window.__MB_STATE_VENDORS;if(Array.isArray(a)&&a.length)return a.map(normV)}catch(e){}try{if(typeof vendors!=='undefined'&&Array.isArray(vendors))return vendors.map(normV)}catch(e){}return[]}
function renderPOVendors(){const box=$('poVendors');if(!box)return;const list=currentVendors().filter(v=>v.enabled!==false&&v.name);if(!list.length){box.innerHTML='<div class="state" style="padding:18px">No vendors available.</div>';return}box.innerHTML=list.map(v=>'<label><input class="poVendorCheck" type="checkbox" value="'+escSafe(v.id)+'" data-name="'+escSafe(v.name)+'"> <span><b>'+escSafe(v.name)+'</b>'+(v.masterOnly?' <small style="color:var(--muted)">(Listing vendor)</small>':'')+'</span></label>').join('')}
async function openPOFixed(){if((typeof session==='function'?session():null)?.role!=='admin')return;try{window.poItems=[];eval('poItems=window.poItems')}catch(e){window.poItems=[]}$('poModal')?.classList.remove('hidden');if(typeof window.renderPOItems==='function')window.renderPOItems();renderPOVendors();try{await window.loadVendors()}catch(e){}renderPOVendors()}
async function lookupSkuFixed(){const sku=$('poSku')?.value.trim();if(!sku)return;try{let r=await window.__MB_GATEWAY({action:'purchaseLookup',token:(typeof token==='function'?token():''),sku});let p=r?.success?normP(r.product||r.data):null;if(!p?.sku){const s=await window.__MB_GATEWAY({action:'searchListing',token:(typeof token==='function'?token():''),query:sku});const arr=s?.data||s?.products||[];const exact=arr.find(x=>String(x.sku||x.SKU||'').trim().toLowerCase()===sku.toLowerCase());if(exact)p=normP(exact)}if(!p?.sku)throw Error(r?.message||'SKU not found in Website Listing.');window.poItems=Array.isArray(window.poItems)?window.poItems:[];if(window.poItems.some(x=>String(x.sku).toLowerCase()===String(p.sku).toLowerCase()))throw Error('SKU already added');window.poItems.push({...p,quantity:1});try{eval('poItems=window.poItems')}catch(e){}$('poSku').value='';if(typeof window.renderPOItems==='function')window.renderPOItems();if($('poLookup'))$('poLookup').textContent='Added '+(p.productName||p.sku);const target=String(p.vendor||p.vendorName||'').trim().toLowerCase();if(target)document.querySelectorAll('.poVendorCheck').forEach(c=>{if(String(c.dataset.name||'').trim().toLowerCase()===target)c.checked=true})}catch(e){if(typeof toastSafe==='function')toastSafe(e.message);else if(typeof toast==='function')toast(e.message)}}
function installPOFix(){window.__MB_RENDER_PO_VENDORS=renderPOVendors;window.openPO=openPOFixed;window.addPOSku=lookupSkuFixed;['quickCreatePO','createPO'].forEach(id=>{const b=$(id);if(!b)return;const n=b.cloneNode(true);b.replaceWith(n);n.addEventListener('click',openPOFixed)});const add=$('poAdd');if(add){const n=add.cloneNode(true);add.replaceWith(n);n.addEventListener('click',lookupSkuFixed)}const sku=$('poSku');if(sku)sku.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();lookupSkuFixed()}});const modal=$('poModal');if(modal){const obs=new MutationObserver(()=>{if(!modal.classList.contains('hidden'))renderPOVendors()});obs.observe(modal,{attributes:true,attributeFilter:['class']})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',installPOFix);else installPOFix();
})();
