(()=>{
'use strict';
const API='https://script.google.com/macros/s/AKfycbwDHq7TB9vSxTlSeG9i55HyuhPzAP8oryRWdLsKhPZVHQubgdIAs8CJ7sknQTJLmabj/exec';
const $=id=>document.getElementById(id);
const session=()=>{try{return JSON.parse(localStorage.getItem('mb_vendor_session')||'null')}catch(e){return null}};
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const toast2=(m,t='info')=>window.toast?window.toast(m,t):null;
const api=p=>new Promise((ok,no)=>{const c='mbq'+Date.now()+Math.random().toString(36).slice(2),s=document.createElement('script');let done=false;const t=setTimeout(()=>finish(no,Error('Gateway timeout.')),30000);function finish(fn,v){if(done)return;done=true;clearTimeout(t);delete window[c];s.remove();fn(v)}window[c]=x=>finish(ok,x);s.onerror=()=>finish(no,Error('Gateway unavailable.'));s.src=API+'?'+new URLSearchParams({...p,callback:c,_:Date.now()});s.async=true;document.head.appendChild(s)});
let vendors=[],lines=[];
function inject(){const tabs=document.querySelector('.admin-tabs'),products=$('productsAdminSection');if(!tabs||!products||$('procurementTabBtn'))return false;if(!document.getElementById('procurementTabBtn')){const b=document.createElement('button');b.id='procurementTabBtn';b.className='tab-btn';b.textContent='Purchase Order';tabs.appendChild(b);b.addEventListener('click',showProcurement,true)}if(!$('procurementAdminSection')){const sec=document.createElement('div');sec.id='procurementAdminSection';sec.className='hidden';sec.innerHTML=`<div class="proc-wrap"><div class="admin-products-head"><div><div class="panel-kicker">PURCHASE ORDER // WEBSITE LISTING</div><h2>Create Vendor Purchase Order</h2><p>Choose a vendor, enter a SKU, fetch the product directly from Website Listing, then enter quantity and PO remarks.</p></div><div class="admin-product-actions"><button id="poExportBtn" class="secondary-btn" type="button">▣ Export PDF</button><button id="poClearBtn" class="secondary-btn" type="button">Clear</button></div></div><div class="panel po-controls"><div class="form-grid"><label>Vendor<select id="poVendorSelect"><option value="">Select vendor…</option></select></label><label>SKU<input id="poSkuInput" placeholder="Enter exact SKU"></label><label>&nbsp;<button id="poFetchBtn" class="primary-small-btn" type="button">Fetch from Website Listing →</button></label></div><div id="poStatus" class="form-message"></div></div><div class="panel"><div class="panel-kicker">ORDER LINES</div><div id="poLines" class="po-lines"><div class="state">No SKUs added yet.</div></div><div class="form-actions"><button id="poSaveBtn" class="primary-btn" type="button">Save Purchase Order <b>→</b></button><span id="poSaveMsg" class="form-message"></span></div></div></div>`;products.parentNode.insertBefore(sec,products.nextSibling);bind()}return true}
function showProcurement(){if(!$('procurementAdminSection'))return;$('usersAdminSection')?.classList.add('hidden');$('productsAdminSection')?.classList.add('hidden');$('procurementAdminSection').classList.remove('hidden');$('usersTabBtn')?.classList.remove('active');$('productsTabBtn')?.classList.remove('active');$('procurementTabBtn')?.classList.add('active');loadVendors()}
function bind(){$('poFetchBtn')?.addEventListener('click',fetchSku);$('poSkuInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();fetchSku()}});$('poVendorSelect')?.addEventListener('change',()=>lines.forEach(x=>{if(!x.vendor)x.vendor=$('poVendorSelect').selectedOptions[0]?.textContent||''}));$('poSaveBtn')?.addEventListener('click',savePO);$('poClearBtn')?.addEventListener('click',()=>{lines=[];drawLines()});$('poExportBtn')?.addEventListener('click',()=>exportLines(lines,'Purchase Order'))}
async function loadVendors(){const s=session();if(!s||s.role!=='admin')return;try{const r=await api({action:'adminVendors',token:s.token});if(!r.success)throw Error(r.message);vendors=r.vendors||[];const sel=$('poVendorSelect');if(!sel)return;const current=sel.value;sel.innerHTML='<option value="">Select vendor…</option>'+vendors.filter(v=>v.enabled).map(v=>`<option value="${esc(v.id)}">${esc(v.name)}</option>`).join('');if(current)sel.value=current}catch(e){toast2(e.message||'Vendor list failed','warn')}}
async function fetchSku(){const s=session(),sku=$('poSkuInput')?.value.trim(),vendor=$('poVendorSelect')?.selectedOptions[0]?.textContent||'';if(!s||s.role!=='admin')return;if(!vendor||!$('poVendorSelect').value){toast2('Select a vendor first.','warn');return}if(!sku){toast2('Enter a SKU.','warn');return}$('poFetchBtn').disabled=true;$('poStatus').textContent='Looking up Website Listing…';try{const r=await api({action:'purchaseLookup',token:s.token,sku});if(!r.success)throw Error(r.message);const p=r.product;const exists=lines.find(x=>String(x.sku).toLowerCase()===String(p.sku).toLowerCase());if(exists){toast2('That SKU is already in this order.','info');return}lines.push({sku:p.sku,productName:p.productName||'',productLink:p.productLink||'',vendor:vendor,price:p.price||'',quantity:'',remarks:'',image:p.image||'',row:p.row});drawLines();$('poSkuInput').value='';$('poStatus').textContent='Fetched from Website Listing.';toast2(p.sku+' added','success')}catch(e){$('poStatus').textContent=e.message||'Lookup failed.';toast2(e.message||'SKU lookup failed','warn')}finally{$('poFetchBtn').disabled=false}}
function drawLines(){const box=$('poLines');if(!box)return;if(!lines.length){box.innerHTML='<div class="state">No SKUs added yet.</div>';return}box.innerHTML='';lines.forEach((p,i)=>{const d=document.createElement('div');d.className='po-line';d.innerHTML=`<div class="po-line-top"><span class="admin-sku">${esc(p.sku)}</span><button class="mini-btn r" type="button">Remove</button></div><div class="form-grid po-edit-grid"><label>Product Name<input data-k="productName" value="${esc(p.productName)}" readonly></label><label>Vendor<input data-k="vendor" value="${esc(p.vendor)}" readonly></label><label>Product Link<input data-k="productLink" value="${esc(p.productLink)}" readonly></label><label>Landing Cost<input data-k="price" value="${esc(p.price)}" readonly></label><label>Quantity<input data-k="quantity" value="${esc(p.quantity)}" placeholder="Enter quantity"></label><label>Remarks<input data-k="remarks" value="${esc(p.remarks)}" placeholder="PO remarks"></label></div><div class="po-source">Product Name, Supplier, Vendor, Product Link and Landing Cost are read directly from <b>Website Listing</b>. Quantity and Remarks belong only to this purchase order and are not written back to the product master.</div>`;d.querySelector('.r').onclick=()=>{lines.splice(i,1);drawLines()};d.querySelectorAll('input:not([readonly])').forEach(inp=>inp.addEventListener('input',()=>{p[inp.dataset.k]=inp.value}));box.appendChild(d)})}
async function savePO(){const s=session(),vendorId=$('poVendorSelect')?.value,msg=$('poSaveMsg');if(!s||s.role!=='admin')return;if(!vendorId){toast2('Select a vendor.','warn');return}if(!lines.length){toast2('Add at least one SKU.','warn');return}const invalid=lines.find(x=>!String(x.quantity||'').trim()||Number(x.quantity)<=0);if(invalid){toast2('Enter a valid quantity for '+invalid.sku,'warn');return}msg.textContent='Saving purchase order…';$('poSaveBtn').disabled=true;try{const r=await api({action:'savePurchaseOrder',token:s.token,vendorId,items:JSON.stringify(lines)});if(!r.success)throw Error(r.message);msg.textContent=r.message+' PO ID: '+(r.poId||'');toast2('Purchase order saved','success');lines=[];drawLines()}catch(e){msg.textContent=e.message||'Save failed.';toast2(e.message||'Purchase save failed','warn')}finally{$('poSaveBtn').disabled=false}}
function selectedVendorName(){return $('poVendorSelect')?.selectedOptions[0]?.textContent||'Vendor'}
function exportLines(rows,title){if(!rows?.length){toast2('Add at least one product before exporting.','warn');return}if(!window.jspdf?.jsPDF){toast2('PDF engine is loading. Refresh and retry.','warn');return}const fields=[['sku','SKU'],['productName','Product Name'],['vendor','Vendor'],['productLink','Product Link'],['price','Landing Cost'],['quantity','Quantity'],['remarks','Remarks']];const chosen=prompt('Enter PDF columns separated by commas. Available: '+fields.map(x=>x[1]).join(', '),'SKU, Product Name, Vendor, Landing Cost, Quantity, Remarks');if(chosen===null)return;const wanted=chosen.split(',').map(x=>x.trim().toLowerCase());const use=fields.filter(f=>wanted.includes(f[1].toLowerCase()));if(!use.length){toast2('No valid columns selected.','warn');return}const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4',compress:true}),W=doc.internal.pageSize.getWidth(),H=doc.internal.pageSize.getHeight(),m=10;doc.setFont('helvetica','bold');doc.setFontSize(15);doc.text('MULTYBYTE PURCHASE ORDER',m,12);doc.setFontSize(8);doc.setFont('helvetica','normal');doc.text(selectedVendorName(),m,18);doc.text(new Date().toLocaleString(),W-m,18,{align:'right'});const colW=(W-2*m)/use.length;let y=28;const rowH=10;function header(){doc.setFillColor(8,15,28);doc.setTextColor(255,255,255);use.forEach((f,i)=>{doc.rect(m+i*colW,y,colW,rowH,'F');doc.text(f[1].slice(0,22),m+i*colW+2,y+6)});y+=rowH;doc.setTextColor(20,30,40)}header();rows.forEach(r=>{if(y+rowH>H-12){doc.addPage();y=15;header()}use.forEach((f,i)=>{doc.setDrawColor(220,225,230);doc.rect(m+i*colW,y,colW,rowH);let v=String(r[f[0]]??'');if(v.length>24)v=v.slice(0,21)+'…';doc.setFontSize(7);doc.text(v,m+i*colW+2,y+6)});y+=rowH});doc.setFontSize(6);doc.text('Generated by Multybyte Partner Portal',m,H-5);doc.save('Multybyte_Purchase_Order_'+selectedVendorName().replace(/[^a-z0-9]+/gi,'_')+'.pdf');toast2('PDF exported with selected columns','success')}
function addExportButtons(){document.querySelectorAll('#productsAdminSection .admin-product-row').forEach(row=>{if(row.querySelector('.mb-select-product'))return;const cb=document.createElement('input');cb.type='checkbox';cb.className='mb-select-product';cb.title='Select for PDF';row.insertBefore(cb,row.firstChild)});document.querySelectorAll('#products .card').forEach(card=>{if(card.querySelector('.mb-select-product'))return;const cb=document.createElement('input');cb.type='checkbox';cb.className='mb-select-product';cb.title='Select for PDF';card.querySelector('.card-body')?.prepend(cb)})}
function boot(){if(!inject()){setTimeout(boot,300);return}const mo=new MutationObserver(addExportButtons);mo.observe(document.body,{childList:true,subtree:true});addExportButtons();setInterval(addExportButtons,1200)}
window.addEventListener('DOMContentLoaded',boot,{once:true});window.addEventListener('load',boot,{once:true});boot();
})();
