/* MULTYBYTE PROCUREMENT V3 — data bridge for the additive V2 UI. */
(function(){
'use strict';
if(window.__MB_PROCUREMENT_V3__)return;window.__MB_PROCUREMENT_V3__=true;
const $=id=>document.getElementById(id), esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const WF='mb_procurement_workflow_v2',ACT='mb_procurement_activity_v2',NOT='mb_procurement_notifications_v2';
let PO=[],PROD=[],VEND=[];
function S(){try{return JSON.parse(localStorage.getItem('mb_vendor_session')||'null')}catch(e){return null}}
function A(){return read(ACT,[])}
function N(){return read(NOT,[])}
function W(){return read(WF,{})}
function status(p){return W()[String(p.poId||p.id)]?.status||String(p.status||'CREATED')}
const FLOW=['DRAFT','SENT','VIEWED','ACCEPTED','PRODUCTION','READY','SHIPPED','RECEIVED','COMPLETED'];
function money(v){const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0}
function notify(type,title,message){const n=N();n.unshift({id:'N'+Date.now(),time:new Date().toISOString(),type,title,message,read:false});write(NOT,n.slice(0,200));renderBell()}
function activity(title,message,meta){const a=A();a.unshift({id:'A'+Date.now(),time:new Date().toISOString(),type:'WORKFLOW',title,message,meta:meta||{},user:S()?.id||'guest'});write(ACT,a.slice(0,500));notify('WORKFLOW',title,message)}
function alerts(){const out=[],now=Date.now(),w=W(),seen={};PO.forEach(p=>{const id=String(p.poId||''),s=status(p);if(!id)return;seen[id]=(seen[id]||0)+1;if(['COMPLETED','RECEIVED','CANCELLED'].includes(s))return;const age=now-(Date.parse(p.createdAt)||now);if(age>3*86400000)out.push({level:'danger',title:'PO overdue for attention',text:id+' has been open for more than 3 days.',po:id});if(['SENT','VIEWED'].includes(s))out.push({level:'warn',title:'Vendor action pending',text:id+' is awaiting acknowledgement.',po:id});});
 const price={};PROD.forEach(p=>{const sku=String(p.sku||'').trim();if(!sku)return;(price[sku]||(price[sku]=[])).push(money(p.price??p.landingCost))});Object.keys(price).forEach(sku=>{const a=price[sku].filter(x=>x>0);if(a.length>1){const min=Math.min(...a),max=Math.max(...a);if(max>min*1.1)out.push({level:'warn',title:'Vendor price variation',text:sku+' has a price range of '+min+' to '+max+'.',sku})}});
 Object.keys(seen).forEach(id=>{if(seen[id]>1)out.push({level:'warn',title:'PO has multiple item rows',text:id+' contains '+seen[id]+' item rows. Review the PO if needed.',po:id})});return out.slice(0,30)}
function metrics(){const c={open:0,pending:0,production:0,ready:0,shipped:0,delayed:0,completed:0},w=W();let value=0;PO.forEach(p=>{const s=status(p);if(!['COMPLETED','RECEIVED','CANCELLED'].includes(s))c.open++;if(['SENT','VIEWED'].includes(s))c.pending++;if(s==='PRODUCTION')c.production++;if(s==='READY')c.ready++;if(s==='SHIPPED')c.shipped++;if(s==='COMPLETED')c.completed++;value+=money(p.price??p.landingCost)*money(p.quantity)});c.delayed=alerts().filter(x=>x.level==='danger').length;return{c,value}}
function renderBell(){let b=$('mbBell'),tr=document.querySelector('.topRight');if(!tr)return;if(!b){b=document.createElement('button');b.id='mbBell';b.className='btn mbBell';tr.insertBefore(b,tr.firstChild)}b.innerHTML='🔔 <span>'+N().filter(x=>!x.read).length+'</span>';b.onclick=showNotifications}
function showNotifications(){const n=N();n.forEach(x=>x.read=true);write(NOT,n);renderBell();const d=document.createElement('div');d.className='modal';d.innerHTML='<div class="modalBox mbNotifyBox"><div class="sectionTitle"><div><span class="eyebrow">NOTIFICATIONS</span><h2 style="margin:4px 0">Action center</h2></div><button class="btn" data-close>Close</button></div>'+(n.length?n.slice(0,50).map(x=>'<div class="mbNotify"><small>'+new Date(x.time).toLocaleString()+'</small><b>'+esc(x.title)+'</b><span>'+esc(x.message)+'</span></div>').join(''):'<div class="state">No notifications.</div>')+'</div>';document.body.appendChild(d);d.onclick=e=>{if(e.target===d||e.target.closest('[data-close]'))d.remove()}}
function renderDashboard(){const d=$('workspaceDashboard');if(!d)return;const m=metrics(),c=m.c,a=alerts(),act=A();let box=$('mbCommandCenter');if(!box){box=document.createElement('div');box.id='mbCommandCenter';d.appendChild(box)}box.innerHTML='<div class="mbHero"><div><span class="eyebrow">PROCUREMENT CONTROL CENTER</span><h2>Everything requiring attention</h2><p>Live counts from the existing Purchase Orders and Website Listing gateway.</p></div><div class="mbHeroValue"><small>ACTIVE PO VALUE</small><b>₹'+Math.round(m.value).toLocaleString('en-IN')+'</b></div></div><div class="mbKpis">'+[['OPEN',c.open,''],['VENDOR ACTION',c.pending,'warn'],['IN PRODUCTION',c.production,''],['READY',c.ready,''],['SHIPPED',c.shipped,''],['DELAYED',c.delayed,'danger'],['COMPLETED',c.completed,'ok']].map(x=>'<div class="mbKpi '+x[2]+'"><small>'+x[0]+'</small><b>'+x[1]+'</b></div>').join('')+'</div><div class="mbSplit"><div class="panel mbAlerts"><div class="sectionTitle"><h3>Smart alerts</h3><span class="pill">'+a.length+' ACTIVE</span></div>'+(a.length?a.map(x=>'<div class="mbAlert '+x.level+'"><i></i><div><b>'+esc(x.title)+'</b><p>'+esc(x.text)+'</p></div></div>').join(''):'<div class="state">No active alerts. Procurement is clear.</div>')+'</div><div class="panel mbActivity"><div class="sectionTitle"><h3>Recent activity</h3></div>'+(act.length?act.slice(0,8).map(x=>'<div class="mbActivityRow"><small>'+new Date(x.time).toLocaleString()+'</small><b>'+esc(x.title)+'</b><span>'+esc(x.message)+'</span></div>').join(''):'<div class="state">No activity yet.</div>')+'</div></div>'}
function renderWorkflow(){const root=$('adminPOSection'),box=$('adminPO');if(!root||!box)return;let panel=$('mbPOWorkflowPanel');if(!panel){panel=document.createElement('div');panel.id='mbPOWorkflowPanel';panel.className='panel';box.parentElement.insertBefore(panel,box)}const unique=[],seen={};PO.forEach(p=>{const id=String(p.poId||'');if(id&&!seen[id]){seen[id]=1;unique.push(p)}});panel.innerHTML='<div class="sectionTitle"><div><span class="eyebrow">WORKFLOW CONTROL</span><h3>PO lifecycle</h3></div><span class="pill">'+unique.length+' POs</span></div><div class="mbPOGrid">'+(unique.length?unique.slice(0,80).map(p=>{const id=String(p.poId),s=status(p),idx=FLOW.indexOf(s.toUpperCase());return '<div class="mbPOCard"><div><b>'+esc(id)+'</b><span class="pill '+(s==='COMPLETED'?'ok':'warn')+'">'+esc(s)+'</span></div><strong>'+esc(p.productName||'Multiple items')+'</strong><small>'+esc(p.vendorName||p.vendor||'—')+' • '+esc(p.sku||'')+' • Qty '+esc(p.quantity??'—')+'</small><div class="mbFlow">'+FLOW.map((x,i)=>'<span class="'+(i<idx?'done ':i===idx?'on ':'')+'">'+x+'</span>').join('')+'</div><div class="mbPOActions"><button class="btn" data-advance="'+esc(id)+'">Advance</button><button class="btn" data-history="'+esc(id)+'">History</button></div></div>'}).join(''):'<div class="state">No POs loaded.</div>')+'</div>';
 panel.querySelectorAll('[data-advance]').forEach(b=>b.onclick=()=>advance(b.dataset.advance));panel.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>history(b.dataset.history))}
function advance(id){const w=W(),old=w[id]?.status||PO.find(p=>String(p.poId)===id)?.status||'CREATED',i=FLOW.indexOf(String(old).toUpperCase()),next=FLOW[Math.min(FLOW.length-1,Math.max(0,i+1))];w[id]=Object.assign({},w[id]||{},{status:next,updatedAt:new Date().toISOString()});write(WF,w);activity('PO '+id+' → '+next,'Status changed from '+old+' to '+next,{poId:id,from:old,to:next});renderDashboard();renderWorkflow()}
function history(id){const a=A().filter(x=>x.meta?.poId===id),d=document.createElement('div');d.className='modal';d.innerHTML='<div class="modalBox"><div class="sectionTitle"><h2>Activity — '+esc(id)+'</h2><button class="btn" data-close>Close</button></div>'+(a.length?a.map(x=>'<div class="mbHistory"><b>'+esc(x.title)+'</b><small>'+new Date(x.time).toLocaleString()+'</small><span>'+esc(x.message)+'</span></div>').join(''):'<div class="state">No activity recorded yet.</div>')+'</div>';document.body.appendChild(d);d.onclick=e=>{if(e.target===d||e.target.closest('[data-close]'))d.remove()}}
async function sync(){const s=S();if(!s||typeof window.api!=='function')return;try{const [p,o,v]=await Promise.all([window.api({action:s.role==='admin'?'adminProducts':'vendorData',token:s.token},20000),window.api({action:'purchaseOrders',token:s.token},20000).catch(()=>null),s.role==='admin'?window.api({action:'adminVendors',token:s.token},20000).catch(()=>null):Promise.resolve(null)]);PROD=(p?.products||p?.data||[]);if(s.role==='admin')PO=(o?.purchaseOrders||o?.data||[]);else{const vo=await window.api({action:'vendorPurchaseOrders',token:s.token},20000).catch(()=>null);PO=(vo?.purchaseOrders||vo?.data||[])}VEND=v?.vendors||[];window.__MB_V2_PRODUCTS=PROD;window.__MB_V2_POS=PO;window.__MB_V2_VENDORS=VEND;renderDashboard();renderWorkflow();renderBell();decorate();}catch(e){console.warn('Procurement V3 sync',e)}}
async function images(limit){const s=S();if(!s||s.role!=='admin'||typeof window.api!=='function')return;const list=PROD.filter(p=>p.productLink&&!p.image).slice(0,limit||15);if(!list.length){window.toast?.('No missing images found.');return}let done=0;for(const p of list){try{const r=await window.api({action:'image',url:p.productLink,sku:p.sku},15000);if(r?.success&&r.image){p.image=r.image;done++;if(p.row)await window.api({action:'saveProduct',token:s.token,row:p.row,image:r.image},15000)}}catch(e){}}window.toast?.(done+' image'+(done===1?'':'s')+' fetched and synced.');activity('Images synced',done+' product images were fetched from listing URLs.');sync()}
function decorate(){const bar=$('adminProductsSection')?.querySelector('.adminToolbar');if(bar&&!bar.querySelector('#mbFetchImages')){const b=document.createElement('button');b.id='mbFetchImages';b.className='btn lime';b.textContent='Fetch Missing Images';b.onclick=()=>images(15);bar.appendChild(b)}document.querySelectorAll('.panel').forEach(x=>x.classList.add('mbSurface'));renderBell()}
function boot(){decorate();sync();setInterval(()=>{if(S())sync()},60000);setInterval(()=>{renderBell();if($('workspaceDashboard')&&!$('workspaceDashboard').classList.contains('hidden'))renderDashboard()},15000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,1100));else setTimeout(boot,1100);
})();
(function(){var s=document.createElement('script');s.src='safe-addons.js?v=20260917-2';s.defer=true;document.head.appendChild(s);var m=document.createElement('script');m.src='manifest-loader.js?v=20260917-1';m.defer=true;document.head.appendChild(m);})();
