/* MULTYBYTE PROCUREMENT V2 — additive layer only.
 * Adds workflow UI, notifications, activity history, command-center dashboard,
 * smart alerts and safe image hydration without replacing existing data/formula logic.
 */
(function(){
'use strict';
if(window.__MB_PROCUREMENT_V2__)return;
window.__MB_PROCUREMENT_V2__=true;
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const WF='mb_procurement_workflow_v2',ACT='mb_procurement_activity_v2',NOT='mb_procurement_notifications_v2';
const state=()=>window.__MB_STATE_POS||window.pos||[];
const products=()=>window.__MB_STATE_MASTER||window.masterProducts||window.products||[];
const vendors=()=>window.__MB_STATE_VENDORS||window.vendors||[];
const sess=()=>{try{return JSON.parse(localStorage.getItem('mb_vendor_session')||'null')}catch(e){return null}};
const api=window.api;
function workflow(){return read(WF,{});}
function activities(){return read(ACT,[]);}
function notes(){return read(NOT,[]);}
function addActivity(type,title,message,meta){const a=activities();a.unshift({id:'A'+Date.now(),time:new Date().toISOString(),type,title,message,meta:meta||{},user:sess()?.id||'guest'});write(ACT,a.slice(0,500));notify(type,title,message);}
function notify(type,title,message){const n=notes();n.unshift({id:'N'+Date.now(),time:new Date().toISOString(),type,title,message,read:false});write(NOT,n.slice(0,200));renderBell();}
function setStatus(poId,status,reason){const w=workflow(),old=w[poId]?.status||'CREATED';w[poId]=Object.assign({},w[poId]||{}, {status,updatedAt:new Date().toISOString(),reason:reason||''});write(WF,w);addActivity('WORKFLOW','PO '+poId+' → '+status,reason||('Status changed from '+old+' to '+status),{poId,from:old,to:status});renderPOEnhancements();drawCommandCenter();}
function poStatus(p){return workflow()[String(p.poId||p.id)]?.status||String(p.status||'CREATED');}
const FLOW=['DRAFT','SENT','VIEWED','ACCEPTED','PRODUCTION','READY','SHIPPED','RECEIVED','COMPLETED'];
function nextStatus(s){const i=FLOW.indexOf(String(s).toUpperCase());return FLOW[Math.min(FLOW.length-1,i<0?1:i+1)];}
function money(v){const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0;}
function buildAlerts(){const out=[],now=Date.now(),w=workflow();
 state().forEach(p=>{const id=String(p.poId||p.id||'');if(!id)return;const s=poStatus(p);if(['COMPLETED','RECEIVED','CANCELLED'].includes(s))return;const age=now-(Date.parse(p.createdAt)||now);if(age>3*86400000)out.push({level:'danger',title:'PO overdue for attention',text:id+' has been open for more than 3 days.',po:id});if(s==='SENT'||s==='VIEWED')out.push({level:'warn',title:'Vendor action pending',text:id+' is awaiting vendor acknowledgement.',po:id});});
 const bySku={};products().forEach(p=>{const sku=String(p.sku||'').trim();if(!sku)return;(bySku[sku]||(bySku[sku]=[])).push(p)});
 Object.keys(bySku).forEach(sku=>{const a=bySku[sku];const prices=a.map(x=>money(x.price??x.landingCost)).filter(x=>x>0);if(prices.length>1){const min=Math.min.apply(null,prices),max=Math.max.apply(null,prices);if(max>min*1.1)out.push({level:'warn',title:'Vendor price variation',text:sku+' has vendor prices ranging from '+min+' to '+max+'.',sku});}});
 const dup={};state().forEach(p=>{const k=String(p.vendorId||p.vendorName||p.vendor||'')+'|'+String(p.sku||'');if(!k||k==='|')return;dup[k]=(dup[k]||0)+1});Object.keys(dup).forEach(k=>{if(dup[k]>1){const z=k.split('|');out.push({level:'warn',title:'Possible duplicate PO',text:z[1]+' appears '+dup[k]+' times for '+z[0]+'.',sku:z[1]})}});
 return out.slice(0,30);
}
function commandMetrics(){const a=state(),w=workflow();const counts={OPEN:0,PENDING:0,PRODUCTION:0,READY:0,SHIPPED:0,DELAYED:0,COMPLETED:0};let value=0;a.forEach(p=>{const s=poStatus(p);if(!['COMPLETED','RECEIVED','CANCELLED'].includes(s))counts.OPEN++;if(['SENT','VIEWED'].includes(s))counts.PENDING++;if(s==='PRODUCTION')counts.PRODUCTION++;if(s==='READY')counts.READY++;if(s==='SHIPPED')counts.SHIPPED++;if(s==='COMPLETED')counts.COMPLETED++;value+=money(p.price??p.landingCost)*money(p.quantity)});counts.DELAYED=buildAlerts().filter(x=>x.level==='danger').length;return {counts,value};}
function drawCommandCenter(){const d=$('workspaceDashboard');if(!d)return;let box=$('mbCommandCenter');if(!box){box=document.createElement('div');box.id='mbCommandCenter';d.insertBefore(box,d.firstChild?.nextSibling||d.firstChild);}
 const m=commandMetrics(),c=m.counts;box.innerHTML='<div class="mbHero"><div><span class="eyebrow">PROCUREMENT CONTROL CENTER</span><h2>Everything requiring attention</h2><p>Live operational view layered on top of the existing Listing Master and PO data.</p></div><div class="mbHeroValue"><small>ACTIVE PO VALUE</small><b>₹'+Math.round(m.value).toLocaleString('en-IN')+'</b></div></div><div class="mbKpis">'+[['OPEN',c.OPEN,''],['VENDOR ACTION',c.PENDING,'warn'],['IN PRODUCTION',c.PRODUCTION,''],['READY',c.READY,''],['SHIPPED',c.SHIPPED,''],['DELAYED',c.DELAYED,'danger'],['COMPLETED',c.COMPLETED,'ok']].map(x=>'<button class="mbKpi '+x[2]+'" data-kpi="'+x[0]+'"><small>'+x[0]+'</small><b>'+x[1]+'</b></button>').join('')+'</div><div class="mbSplit"><div class="panel mbAlerts"><div class="sectionTitle"><h3>Smart alerts</h3><span class="pill">'+buildAlerts().length+' ACTIVE</span></div>'+renderAlerts(buildAlerts())+'</div><div class="panel mbActivity"><div class="sectionTitle"><h3>Recent activity</h3><button class="btn" id="mbClearActivity">Clear local activity</button></div>'+renderActivityMini()+'</div></div>';
 box.querySelectorAll('[data-kpi]').forEach(b=>b.onclick=()=>{showSectionSafe('po');const f=$('mbPOSearch');if(f)f.value='';});box.querySelector('#mbClearActivity')?.addEventListener('click',()=>{if(confirm('Clear portal activity history stored in this browser?')){write(ACT,[]);drawCommandCenter()}});
}
function renderAlerts(a){if(!a.length)return '<div class="state mbEmpty">No active alerts. Procurement is clear.</div>';return '<div class="mbAlertList">'+a.map(x=>'<div class="mbAlert '+x.level+'"><span class="mbAlertDot"></span><div><b>'+esc(x.title)+'</b><p>'+esc(x.text)+'</p></div></div>').join('')+'</div>';}
function renderActivityMini(){const a=activities();if(!a.length)return '<div class="state mbEmpty">No local activity yet.</div>';return '<div class="mbActivityList">'+a.slice(0,8).map(x=>'<div class="mbActivityRow"><span class="mbTime">'+new Date(x.time).toLocaleString()+'</span><b>'+esc(x.title)+'</b><span>'+esc(x.message)+'</span></div>').join('')+'</div>';}
function renderBell(){const n=notes(),unread=n.filter(x=>!x.read).length;let b=$('mbBell');if(!b){const tr=document.querySelector('.topRight');if(!tr)return;b=document.createElement('button');b.id='mbBell';b.className='btn mbBell';tr.insertBefore(b,tr.firstChild);}b.innerHTML='🔔 <span>'+unread+'</span>';b.onclick=()=>showNotifications();}
function showNotifications(){const n=notes();n.forEach(x=>x.read=true);write(NOT,n);renderBell();const old=$('mbNotifyModal');old?.remove();const d=document.createElement('div');d.id='mbNotifyModal';d.className='modal';d.innerHTML='<div class="modalBox mbNotifyBox"><div class="sectionTitle"><div><span class="eyebrow">NOTIFICATIONS</span><h2 style="margin:4px 0">Action center</h2></div><button class="btn" data-close>Close</button></div>'+((n.length)?n.slice(0,50).map(x=>'<div class="mbNotify '+esc(x.type||'INFO')+'"><small>'+new Date(x.time).toLocaleString()+'</small><b>'+esc(x.title)+'</b><span>'+esc(x.message)+'</span></div>').join(''):'<div class="state">No notifications.</div>')+'</div>';document.body.appendChild(d);d.onclick=e=>{if(e.target===d||e.target.closest('[data-close]'))d.remove()};}
function workflowBar(p){const s=poStatus(p).toUpperCase(),idx=FLOW.indexOf(s);return '<div class="mbFlow">'+FLOW.map((x,i)=>'<span class="'+(i<idx?'done ':i===idx?'on ':'')+'">'+x+'</span>').join('')+'</div>';}
function enhancePORow(p){const id=String(p.poId||p.id||''),s=poStatus(p);return '<div class="mbPOCard"><div><b>'+esc(id)+'</b><span class="pill '+(s==='COMPLETED'?'ok':s==='READY'||s==='SHIPPED'?'':'warn')+'">'+esc(s)+'</span></div><strong>'+esc(p.productName||'—')+'</strong><small>'+esc(p.sku||'')+' • '+esc(p.vendorName||p.vendor||'—')+' • Qty '+esc(p.quantity??'—')+'</small>'+workflowBar(p)+'<div class="mbPOActions"><button class="btn" data-po-next="'+esc(id)+'">Advance</button><button class="btn" data-po-event="'+esc(id)+'">History</button><button class="btn" data-po-smart="'+esc(id)+'">Alerts</button></div></div>';}
function renderPOEnhancements(){const box=$('adminPO');if(!box)return;let panel=$('mbPOWorkflowPanel');if(!panel){panel=document.createElement('div');panel.id='mbPOWorkflowPanel';panel.className='panel';box.parentElement.insertBefore(panel,box);}const a=state().slice(0,60);panel.innerHTML='<div class="sectionTitle"><div><span class="eyebrow">WORKFLOW CONTROL</span><h3>PO lifecycle</h3></div><span class="pill">'+a.length+' RECORDS</span></div><div class="mbPOGrid">'+(a.length?a.map(enhancePORow).join(''):'<div class="state">No POs loaded.</div>')+'</div>';
 panel.querySelectorAll('[data-po-next]').forEach(b=>b.onclick=()=>{const id=b.dataset.poNext,p=a.find(x=>String(x.poId||x.id)===id),s=poStatus(p),n=nextStatus(s);setStatus(id,n);});panel.querySelectorAll('[data-po-event]').forEach(b=>b.onclick=()=>showHistory(b.dataset.poEvent));panel.querySelectorAll('[data-po-smart]').forEach(b=>b.onclick=()=>showSmartForPO(b.dataset.poSmart));}
function showHistory(id){const a=activities().filter(x=>x.meta?.poId===id);const d=document.createElement('div');d.className='modal';d.innerHTML='<div class="modalBox"><div class="sectionTitle"><h2>Activity — '+esc(id)+'</h2><button class="btn" data-close>Close</button></div>'+(a.length?a.map(x=>'<div class="mbHistory"><b>'+esc(x.title)+'</b><small>'+new Date(x.time).toLocaleString()+'</small><span>'+esc(x.message)+'</span></div>').join(''):'<div class="state">No activity recorded yet.</div>')+'</div>';document.body.appendChild(d);d.onclick=e=>{if(e.target===d||e.target.closest('[data-close]'))d.remove()};}
function showSmartForPO(id){const a=buildAlerts().filter(x=>x.po===id);const d=document.createElement('div');d.className='modal';d.innerHTML='<div class="modalBox"><div class="sectionTitle"><h2>Smart checks — '+esc(id)+'</h2><button class="btn" data-close>Close</button></div>'+renderAlerts(a)+'</div>';document.body.appendChild(d);d.onclick=e=>{if(e.target===d||e.target.closest('[data-close]'))d.remove()};}
async function hydrateImages(limit){const s=sess();if(!s||s.role!=='admin'||typeof window.api!=='function')return;const list=products().filter(p=>p.productLink&&!p.image).slice(0,limit||10);if(!list.length){toastSafe('No missing product images in the current data.');return;}let done=0;for(const p of list){try{const r=await window.api({action:'image',url:p.productLink,sku:p.sku},15000);if(r?.success&&r.image){p.image=r.image;done++;if(p.row)await window.api({action:'saveProduct',token:s.token,row:p.row,image:r.image},15000);}}catch(e){}}drawAllSafe();toastSafe(done+' product image'+(done===1?'':'s')+' fetched and synced.');addActivity('IMAGE_SYNC','Product images synced',done+' missing product images were fetched safely.');}
function addImageButton(){if(sess()?.role!=='admin')return;const sec=$('adminProductsSection');if(!sec)return;const bar=sec.querySelector('.adminToolbar');if(bar&&!bar.querySelector('#mbFetchImages')){const b=document.createElement('button');b.id='mbFetchImages';b.className='btn lime';b.textContent='Fetch Missing Images';b.onclick=()=>hydrateImages(15);bar.appendChild(b);}}
function patchCards(){document.querySelectorAll('.photo img').forEach(img=>{img.onerror=()=>{img.closest('.photo')?.classList.add('mbImageFail');img.style.display='none';};});}
function decoratePages(){document.querySelectorAll('.panel').forEach(p=>p.classList.add('mbSurface'));document.querySelectorAll('.pageHead').forEach(p=>p.classList.add('mbPageHead'));addImageButton();patchCards();renderBell();}
function drawAllSafe(){try{window.drawAdminProducts?.()}catch(e){}try{window.drawVendor?.()}catch(e){}try{window.drawDashboard?.()}catch(e){}decoratePages();setTimeout(renderPOEnhancements,50);}
function showSectionSafe(n){try{window.showSection?.(n)}catch(e){}setTimeout(()=>{decoratePages();if(n==='dashboard')drawCommandCenter();if(n==='po')renderPOEnhancements()},100);}
function toastSafe(m){try{window.toast?.(m)}catch(e){alert(m)}}
function installHooks(){
 const oldShow=window.showSection;if(oldShow&&!oldShow.__v2){const w=function(n){const r=oldShow.apply(this,arguments);setTimeout(()=>{decoratePages();if(n==='dashboard')drawCommandCenter();if(n==='po')renderPOEnhancements()},80);return r};w.__v2=true;window.showSection=w;}
 const oldLoad=window.loadPO;if(oldLoad&&!oldLoad.__v2){const w=async function(){const r=await oldLoad.apply(this,arguments);setTimeout(()=>{renderPOEnhancements();drawCommandCenter()},100);return r};w.__v2=true;window.loadPO=w;}
 const oldAdmin=window.loadAdmin;if(oldAdmin&&!oldAdmin.__v2){const w=async function(){const r=await oldAdmin.apply(this,arguments);setTimeout(()=>{drawCommandCenter();decoratePages();renderPOEnhancements()},150);return r};w.__v2=true;window.loadAdmin=w;}
 const oldVendor=window.loadVendor;if(oldVendor&&!oldVendor.__v2){const w=async function(){const r=await oldVendor.apply(this,arguments);setTimeout(()=>{decoratePages();drawCommandCenter()},150);return r};w.__v2=true;window.loadVendor=w;}
}
function boot(){installHooks();decoratePages();drawCommandCenter();renderPOEnhancements();
 if(!activities().length)addActivity('SYSTEM','Procurement V2 ready','Workflow, notifications, activity history, command center and smart alerts are active.');
 setTimeout(()=>{installHooks();decoratePages();drawCommandCenter();renderPOEnhancements()},900);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,700));else setTimeout(boot,700);
})();
