/* MULTYBYTE SAFE ADDONS — theme, PWA install, product-link image recovery. */
(function(){'use strict';if(window.__MB_SAFE_ADDONS__)return;window.__MB_SAFE_ADDONS__=1;
const API='https://script.google.com/macros/s/AKfycbwCGKZiV57bzmspcr5W2aVF5R7SpbwEqCs911boTjJbkPYvFEZJ-QNL0iD42qrxXfT9/exec';
const K='mb_theme_mode_v2';const $=s=>document.querySelector(s);const by=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function css(){if(by('mbSafeCss'))return;const s=document.createElement('style');s.id='mbSafeCss';s.textContent=`
html[data-theme=light]{color-scheme:light;--bg:#f5f8f7;--bg2:#eaf1ef;--panel:#fff;--panel2:#f7faf9;--white:#10201e;--muted:#58706b;--line:#cbd9d5;--lime:#4e8500;--teal:#087f70;--danger:#c83c3c;--amber:#936100;--shadow:0 18px 55px #17332a18}html[data-theme=light] body{background:var(--bg);color:var(--white)}html[data-theme=light] .portalTop{background:#ffffffef}html[data-theme=light] .panel,html[data-theme=light] .card,html[data-theme=light] .modalBox{background:#fff;color:var(--white)}html[data-theme=light] .field,html[data-theme=light] select.field,html[data-theme=light] .roleSwitch{background:#fff;color:#10201e}html[data-theme=light] .table th{background:#eef5f2;color:#45615b}html[data-theme=light] .metric,html[data-theme=light] .meta div{background:#f5f8f7;border-color:#d8e3e0}html[data-theme=light] .loginCard{background:#ffffffdd;border-color:#d6e2df}html[data-theme=light] .photo{background:#f7faf9}
.mbSafeControls{display:flex;gap:6px;align-items:center}.mbInstall{display:none}.mbImageRetry{position:absolute;right:8px;bottom:8px;z-index:5}.mbImgBusy{opacity:.5}.mbLoginTheme{position:absolute;right:18px;top:18px}.mbLightFix{color:#10201e!important}@media(max-width:650px){.mbTheme{font-size:0}.mbTheme:before{content:'☀ / ◐';font-size:15px}.mbInstall{display:inline-flex!important}.mbSafeControls .btn{padding:8px 9px}}
`;document.head.appendChild(s)}
function theme(mode){mode=mode==='light'?'light':'dark';document.documentElement.dataset.theme=mode;localStorage.setItem(K,mode);const b=by('mbTheme');if(b)b.textContent=mode==='dark'?'☀ White':'◐ Black';const m=$('meta[name="theme-color"]');if(m)m.content=mode==='dark'?'#071b1b':'#f5f8f7'}
function controls(){if(!by('mbTheme')){const top=$('.topRight');if(top){const w=document.createElement('span');w.className='mbSafeControls';w.innerHTML='<button id="mbTheme" class="btn mbTheme" type="button">Theme</button><button id="mbInstall" class="btn primary mbInstall" type="button">Install App</button>';top.prepend(w);by('mbTheme').onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark');by('mbInstall').onclick=install}}const card=$('.loginCard');if(card&&!by('mbLoginTheme')){const b=document.createElement('button');b.id='mbLoginTheme';b.className='btn mbLoginTheme';b.textContent='☀ / ◐ Theme';card.style.position='relative';card.appendChild(b);b.onclick=()=>theme(document.documentElement.dataset.theme==='dark'?'light':'dark')}}
let installEvent=null;function pwa(){if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{});addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;const b=by('mbInstall');if(b)b.style.display='inline-flex'});addEventListener('appinstalled',()=>{installEvent=null;by('mbInstall')?.style&& (by('mbInstall').style.display='none')})}async function install(){if(installEvent){installEvent.prompt();try{await installEvent.userChoice}catch(e){}installEvent=null}else alert('Use Chrome menu → Install Multybyte / Add to Home screen.')} 
function jsonp(url,timeout=16000){return new Promise((resolve,reject)=>{let done=0,t,sc;const cb='mbsafe_'+Date.now()+'_'+Math.random().toString(36).slice(2);const end=(ok,v)=>{if(done)return;done=1;clearTimeout(t);sc?.remove();try{delete window[cb]}catch(e){}ok?resolve(v):reject(e||Error('failed'))};window[cb]=v=>end(true,v);sc=document.createElement('script');sc.src=url+'&callback='+cb+'&_safe='+Date.now();sc.onerror=()=>end(false);document.head.appendChild(sc);t=setTimeout(()=>end(false),timeout)})}
async function resolve(p){if(!p?.productLink)return'';const key='mb_safe_img_'+String(p.sku||p.productLink).toLowerCase();try{const old=localStorage.getItem(key);if(old)return old}catch(e){}let u='';try{const r=await jsonp(API+'?action=image&url='+encodeURIComponent(p.productLink)+'&sku='+encodeURIComponent(p.sku||''));u=String(r?.image||r?.url||'').trim()}catch(e){}if(u)try{localStorage.setItem(key,u)}catch(e){}return u}
function state(sku){const a=[...(window.__MB_STATE_PRODUCTS||[]),...(window.__MB_STATE_MASTER||[])];return a.find(p=>String(p?.sku||'').trim().toLowerCase()===String(sku||'').trim().toLowerCase())}
async function fix(img){if(!img||img.dataset.safeFix)return;img.dataset.safeFix='1';const card=img.closest('.card');const sku=card?.querySelector('.sku')?.textContent?.replace(/^SKU\s*:?\s*/i,'').trim()||'';const p=state(sku);if(!p?.productLink){img.dataset.safeFix='0';return}img.classList.add('mbImgBusy');const u=await resolve(p);if(u){p.image=u;img.src=u}img.classList.remove('mbImgBusy');img.dataset.safeFix='0'}
function images(){document.querySelectorAll('.card .photo img').forEach(img=>{if(!img.dataset.safeBound){img.dataset.safeBound=1;img.addEventListener('error',()=>fix(img))}if(!img.getAttribute('src')||img.getAttribute('src')==='about:blank')fix(img)})}
function wrap(n){const f=window[n];if(typeof f!=='function'||f.__safe)return;const w=function(){const r=f.apply(this,arguments);setTimeout(images,150);setTimeout(images,1200);return r};w.__safe=1;window[n]=w}
function boot(){css();theme(localStorage.getItem(K)||'dark');controls();pwa();['drawAdminProducts','drawVendor','drawDashboard'].forEach(wrap);images();new MutationObserver(images).observe(document.body,{subtree:true,childList:true});setTimeout(images,1000);setTimeout(images,3000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,900));else setTimeout(boot,900);
})();
