const CACHE='multybyte-china-purchase-v16';
const APP_FILES=['./','./index.html','./style.css','./enhancements.css','./login-reimagined.css','./login-side-ultra.css','./procurement-upgrades.css','./api-bridge.js','./app.js','./admin-products.js','./admin-enhancements.js','./portal-upgrades.js','./login-side-ultra.js','./executive-dashboard.js','./selected-pdf-ui.js','./preview-bridge.js','./procurement-command-center.js','./procurement-revamp.js','./manifest.json','./icon-192.svg','./icon-512.svg'];
const OLD_API='https://script.google.com/macros/s/AKfycbwDHq7TB9vSxTlSeG9i55HyuhPzAP8oryRWdLsKhPZVHQubgdIAs8CJ7sknQTJLmabj/exec';
const NEW_API='https://script.google.com/macros/s/AKfycbxc49T5iqv7V5XvZZciOyaW6a4_CGhjy6hjuxVwHehE8bOX8SGlTL-RJnbC4xpafWWx/exec';
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(APP_FILES)).catch(()=>{}));self.skipWaiting()});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))));self.clients.claim()});
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);
if(url.origin==='https://script.google.com'&&url.href.startsWith(OLD_API)){const target=new URL(NEW_API);target.search=url.search;event.respondWith(fetch(new Request(target.toString(),{method:'GET',headers:req.headers,mode:'cors',credentials:'omit',redirect:'follow'})));return;}
if(url.pathname.endsWith('/data.json')||url.hostname.includes('cdn.jsdelivr.net'))return;
if(url.origin!==self.location.origin)return;
event.respondWith((async()=>{const cached=await caches.match(req);const network=fetch(req,{cache:'no-store'}).then(response=>{if(response&&response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(req,copy)).catch(()=>{})}return response}).catch(()=>null);if(cached){network.catch(()=>{});return cached}const response=await network;return response||new Response('Offline',{status:503,headers:{'Content-Type':'text/plain'}})})())});