const MB_PORTAL={SPREADSHEET_ID:'1VsuPiZuuNucfhMidXUgIxHVBYMoTCL6urMOJkLK5_hU',MASTER_SHEET:'Website Listing',VENDOR_SHEET:'VENDORS',PO_SHEET:'PURCHASE_ORDERS',SESSION_TTL:21600,ADMIN_PROPERTY:'MB_ADMIN_HASH',ADMIN_ID_PROPERTY:'MB_ADMIN_ID',DEFAULT_ADMIN_ID:'admin',DEFAULT_ADMIN_HASH:'240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',VENDOR_HEADERS:['SKU','Product Name','Quantity','Supplier','Product Link','Image','Landing Cost','Remarks','PO ID','Created At','Status'],PO_HEADERS:['PO ID','Created At','Created By','Vendor ID','Vendor Name','SKU','Product Name','Supplier','Landing Cost','Quantity','Remarks','Product Link','Image','Status'],COL:{NAME:1,SKU:2,LINK:9,PRICE:27,SUPPLIER:69,VENDOR:74}};
function doGet(e){try{const p=e&&e.parameter?e.parameter:{},a=String(p.action||'data').trim();let r;switch(a){case'data':r=publicSyncData_();break;case'login':r=login_(p);break;case'vendorData':r=vendorData_(p);break;case'adminVendors':case'vendors/list':r=adminVendors_(p);break;case'saveVendor':r=saveVendor_(p);break;case'adminProducts':case'adminProductMatrix':case'masterProducts':r=adminProducts_(p);break;case'saveProduct':case'adminSaveProduct':r=saveProduct_(p);break;case'deleteProduct':case'adminDeleteProduct':r=deleteProduct_(p);break;case'purchaseLookup':case'listingProduct':case'preparePOProduct':r=purchaseLookup_(p);break;case'searchListing':r=searchListing_(p);break;case'savePurchaseOrder':case'createPO':r=savePurchaseOrder_(p);break;case'purchaseOrders':case'listPurchaseOrders':r=purchaseOrders_(p);break;case'vendorPurchaseOrders':r=vendorPurchaseOrders_(p);break;case'clearVendorPurchase':r=clearVendorPurchase_(p);break;case'portalStats':case'listingStats':r=portalStats_(p);break;case'logout':r=logout_(p);break;case'setup':r=setupVendorPortal();break;default:r={success:false,message:'Unknown action: '+a,code:'UNKNOWN_ACTION'}}return output_(r,p.callback)}catch(err){return output_({success:false,message:String(err&&err.message||err),code:'SERVER_ERROR'},e&&e.parameter&&e.parameter.callback)}}
function setupVendorPortal(){const ss=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID);if(!ss.getSheetByName(MB_PORTAL.MASTER_SHEET))throw new Error('Website Listing sheet not found.');ensureSheet_(ss,MB_PORTAL.VENDOR_SHEET,['User ID','User Name','Sheet Name','Enabled','Password Hash']);ensureSheet_(ss,MB_PORTAL.PO_SHEET,MB_PORTAL.PO_HEADERS);ensureAdmin_();return{success:true,message:'Website Listing portal setup complete.'}}
function ensureSheet_(ss,name,headers){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);if(sh.getLastRow()===0)sh.getRange(1,1,1,headers.length).setValues([headers]);sh.setFrozenRows(1);sh.getRange(1,1,1,headers.length).setFontWeight('bold');return sh}
function ensureAdmin_(){const x=PropertiesService.getScriptProperties();if(!x.getProperty(MB_PORTAL.ADMIN_PROPERTY))x.setProperty(MB_PORTAL.ADMIN_PROPERTY,MB_PORTAL.DEFAULT_ADMIN_HASH);if(!x.getProperty(MB_PORTAL.ADMIN_ID_PROPERTY))x.setProperty(MB_PORTAL.ADMIN_ID_PROPERTY,MB_PORTAL.DEFAULT_ADMIN_ID)}
function setAdminPassword_(){const ui=SpreadsheetApp.getUi(),id=ui.prompt('Admin ID','Enter the admin login ID:',ui.ButtonSet.OK_CANCEL);if(id.getSelectedButton()!==ui.Button.OK)return;const pw=ui.prompt('Admin Password','Enter the admin password:',ui.ButtonSet.OK_CANCEL);if(pw.getSelectedButton()!==ui.Button.OK||!pw.getResponseText())throw new Error('Admin password was not set.');PropertiesService.getScriptProperties().setProperty(MB_PORTAL.ADMIN_PROPERTY,hash_(pw.getResponseText()));PropertiesService.getScriptProperties().setProperty(MB_PORTAL.ADMIN_ID_PROPERTY,id.getResponseText().trim()||MB_PORTAL.DEFAULT_ADMIN_ID)}
function resetAdminPassword(){setAdminPassword_()}
function login_(p){const role=String(p.role||'vendor').toLowerCase(),id=String(p.id||'').trim(),password=String(p.password||'');if(!id||!password)return{success:false,message:'ID and password are required.'};if(role==='admin'){ensureAdmin_();const ai=PropertiesService.getScriptProperties().getProperty(MB_PORTAL.ADMIN_ID_PROPERTY)||MB_PORTAL.DEFAULT_ADMIN_ID,ah=PropertiesService.getScriptProperties().getProperty(MB_PORTAL.ADMIN_PROPERTY);if(id!==ai||hash_(password)!==ah)return{success:false,message:'Invalid admin ID or password.'};return{success:true,role:'admin',id:ai,name:'Administrator',token:createSession_({role:'admin',id:ai,name:'Administrator'})}}const v=findVendor_(id);if(!v||!v.enabled)return{success:false,message:'Vendor account is disabled or not found.'};if(hash_(password)!==v.passwordHash)return{success:false,message:'Invalid vendor ID or password.'};return{success:true,role:'vendor',id:v.id,name:v.name,token:createSession_({role:'vendor',id:v.id,name:v.name,sheetName:v.sheetName})}}
function vendorData_(p){const s=getSession_(p.token,'vendor');if(!s)return{success:false,message:'Session expired. Please sign in again.'};const sh=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID).getSheetByName(s.sheetName);if(!sh)return{success:false,message:'Assigned vendor workspace no longer exists.'};const data=readVendorSheet_(sh);touchSession_(p.token,s);return{success:true,vendorId:s.id,vendorName:s.name,sheetName:s.sheetName,updated:new Date().toISOString(),data:data}}
function adminVendors_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const sh=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID).getSheetByName(MB_PORTAL.VENDOR_SHEET);if(!sh||sh.getLastRow()<2)return{success:true,vendors:[]};const rows=sh.getRange(2,1,sh.getLastRow()-1,5).getDisplayValues();return{success:true,vendors:rows.filter(r=>r[0]).map(r=>({id:r[0],name:r[1],sheetName:r[2],enabled:String(r[3]).toLowerCase()==='true'}))}}
function saveVendor_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const id=String(p.id||'').trim(),name=String(p.name||'').trim(),password=String(p.password||''),enabled=p.enabled===undefined?true:String(p.enabled).toLowerCase()==='true';if(!id||!name)return{success:false,message:'User ID and vendor name are required.'};const ss=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),sh=ensureSheet_(ss,MB_PORTAL.VENDOR_SHEET,['User ID','User Name','Sheet Name','Enabled','Password Hash']),rows=sh.getLastRow()>1?sh.getRange(2,1,sh.getLastRow()-1,5).getValues():[];let row=0,oldHash='',oldSheet='';for(let i=0;i<rows.length;i++)if(String(rows[i][0]).trim()===id){row=i+2;oldHash=String(rows[i][4]||'');oldSheet=String(rows[i][2]||'');break}const sheetName=row&&oldSheet?oldSheet:uniqueVendorSheetName_(ss,name,id);ensureVendorSheet_(ss,sheetName);if(!row){if(!password)return{success:false,message:'Password is required for a new vendor.'};sh.appendRow([id,name,sheetName,enabled,hash_(password)])}else{if(password)oldHash=hash_(password);sh.getRange(row,1,1,5).setValues([[id,name,sheetName,enabled,oldHash]])}return{success:true,message:row?'Vendor updated.':'Vendor created.',vendor:{id:id,name:name,sheetName:sheetName,enabled:enabled}}}
function uniqueVendorSheetName_(ss,name,id){const base=sanitizeSheetName_(name||id||'Vendor')||'Vendor';let candidate=base,n=2;while(ss.getSheetByName(candidate))candidate=(base.slice(0,95)+' '+n++).slice(0,100);return candidate}
function sanitizeSheetName_(s){return String(s).replace(/[\\/?*\[\]:]/g,' ').replace(/^'+|'+$/g,'').trim().slice(0,100)}
function ensureVendorSheet_(ss,name){return ensureSheet_(ss,name,MB_PORTAL.VENDOR_HEADERS)}
function getMasterSheet_(){const ss=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),sh=ss.getSheetByName(MB_PORTAL.MASTER_SHEET);if(!sh)throw new Error('Website Listing sheet not found.');return sh}
function readMasterRows_(){const sh=getMasterSheet_(),lastRow=sh.getLastRow(),lastCol=Math.max(sh.getLastColumn(),MB_PORTAL.COL.VENDOR);if(lastRow<2)return{sh:sh,rows:[],lastCol:lastCol};return{sh:sh,rows:sh.getRange(2,1,lastRow-1,lastCol).getDisplayValues(),lastCol:lastCol}}
function normalizeMasterProduct_(r,n){return{row:n,sku:String(r[MB_PORTAL.COL.SKU-1]||'').trim(),productName:String(r[MB_PORTAL.COL.NAME-1]||'').trim(),productLink:String(r[MB_PORTAL.COL.LINK-1]||'').trim(),price:String(r[MB_PORTAL.COL.PRICE-1]||'').trim(),landingCost:String(r[MB_PORTAL.COL.PRICE-1]||'').trim(),supplier:String(r[MB_PORTAL.COL.SUPPLIER-1]||'').trim(),vendor:String(r[MB_PORTAL.COL.VENDOR-1]||'').trim(),image:'',quantity:'',remarks:'',source:'Website Listing'}}
function adminProducts_(p){const s=getSession_(p.token,'admin');if(!s)return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const x=readMasterRows_(),data=x.rows.map((r,i)=>normalizeMasterProduct_(r,i+2)).filter(p=>p.sku||p.productName);touchSession_(p.token,s);return{success:true,source:'Website Listing',updated:new Date().toISOString(),total:data.length,data:data}}
function saveProduct_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const sh=getMasterSheet_(),row=Number(p.row||0),lastCol=Math.max(sh.getLastColumn(),MB_PORTAL.COL.VENDOR);if(row<2||row>sh.getLastRow())return{success:false,message:'A valid Website Listing row is required.'};const v=sh.getRange(row,1,1,lastCol).getValues()[0];if(p.sku!==undefined)v[MB_PORTAL.COL.SKU-1]=p.sku;if(p.productName!==undefined)v[MB_PORTAL.COL.NAME-1]=p.productName;if(p.productLink!==undefined)v[MB_PORTAL.COL.LINK-1]=p.productLink;if(p.price!==undefined)v[MB_PORTAL.COL.PRICE-1]=p.price;if(p.vendor!==undefined)v[MB_PORTAL.COL.VENDOR-1]=p.vendor;if(p.supplier!==undefined)v[MB_PORTAL.COL.SUPPLIER-1]=p.supplier;sh.getRange(row,1,1,lastCol).setValues([v]);return{success:true,message:'Website Listing product updated.',product:normalizeMasterProduct_(sh.getRange(row,1,1,lastCol).getDisplayValues()[0],row)}}
function deleteProduct_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const sh=getMasterSheet_(),row=Number(p.row||0);if(row<2||row>sh.getLastRow())return{success:false,message:'Invalid Website Listing row.'};sh.deleteRow(row);return{success:true,message:'Website Listing product removed.'}}
function purchaseLookup_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const sku=String(p.sku||'').trim();if(!sku)return{success:false,message:'Enter a SKU.'};const x=readMasterRows_();for(let i=0;i<x.rows.length;i++){const product=normalizeMasterProduct_(x.rows[i],i+2);if(product.sku.toLowerCase()===sku.toLowerCase()){product.image=findImage_(product.productLink)||'';return{success:true,source:'Website Listing',product:product}}}return{success:false,message:'SKU not found in Website Listing.',code:'SKU_NOT_FOUND'}}
function searchListing_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const q=String(p.query||p.sku||'').trim().toLowerCase();if(!q)return{success:true,data:[]};const x=readMasterRows_(),data=[];for(let i=0;i<x.rows.length&&data.length<50;i++){const product=normalizeMasterProduct_(x.rows[i],i+2);if(product.sku.toLowerCase().includes(q)||product.productName.toLowerCase().includes(q))data.push(product)}return{success:true,source:'Website Listing',total:data.length,data:data}}
function savePurchaseOrder_(p){const s=getSession_(p.token,'admin');if(!s)return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const vendorId=String(p.vendorId||'').trim();let items;try{items=JSON.parse(String(p.items||'[]'))}catch(e){return{success:false,message:'Invalid PO items.'}}if(!vendorId||!Array.isArray(items)||!items.length)return{success:false,message:'Select a vendor and at least one SKU.'};const vendor=findVendor_(vendorId);if(!vendor)return{success:false,message:'Vendor account not found.'};const x=readMasterRows_(),map={};x.rows.forEach((r,i)=>{const sku=String(r[MB_PORTAL.COL.SKU-1]||'').trim().toLowerCase();if(sku)map[sku]={row:r,rowNumber:i+2}});const ss=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),vsh=ensureVendorSheet_(ss,vendor.sheetName),posh=ensureSheet_(ss,MB_PORTAL.PO_SHEET,MB_PORTAL.PO_HEADERS),poId='PO-'+Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyyMMdd-HHmmss')+'-'+Utilities.getUuid().slice(0,6).toUpperCase(),now=new Date(),vr=[],pr=[];items.forEach(item=>{const sku=String(item.sku||'').trim();if(!sku)return;const hit=map[sku.toLowerCase()];if(!hit)throw new Error('SKU not found in Website Listing: '+sku);const product=normalizeMasterProduct_(hit.row,hit.rowNumber),qty=String(item.quantity||'').trim(),remarks=String(item.remarks||'').trim(),image=String(item.image||findImage_(product.productLink)||'');vr.push([product.sku,product.productName,qty,product.supplier,product.productLink,image,product.price,remarks,poId,now,'CREATED']);pr.push([poId,now,s.id,vendor.id,vendor.name,product.sku,product.productName,product.supplier,product.price,qty,remarks,product.productLink,image,'CREATED'])});if(!vr.length)return{success:false,message:'No valid PO items.'};vsh.getRange(vsh.getLastRow()+1,1,vr.length,MB_PORTAL.VENDOR_HEADERS.length).setValues(vr);posh.getRange(posh.getLastRow()+1,1,pr.length,MB_PORTAL.PO_HEADERS.length).setValues(pr);touchSession_(p.token,s);return{success:true,message:vr.length+' purchase item'+(vr.length===1?'':'s')+' saved.',poId:poId,vendor:vendor,items:vr.map(r=>({sku:r[0],productName:r[1],quantity:r[2],supplier:r[3],productLink:r[4],image:r[5],price:r[6],remarks:r[7]})),savedAt:now.toISOString()}}
function purchaseOrders_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const sh=ensureSheet_(SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),MB_PORTAL.PO_SHEET,MB_PORTAL.PO_HEADERS);if(sh.getLastRow()<2)return{success:true,data:[],total:0};const rows=sh.getRange(2,1,sh.getLastRow()-1,MB_PORTAL.PO_HEADERS.length).getDisplayValues();return{success:true,total:rows.length,data:rows.reverse().map(r=>({poId:r[0],createdAt:r[1],createdBy:r[2],vendorId:r[3],vendor:r[4],sku:r[5],productName:r[6],supplier:r[7],price:r[8],quantity:r[9],remarks:r[10],productLink:r[11],image:r[12],status:r[13]}))}}
function vendorPurchaseOrders_(p){const s=getSession_(p.token,'vendor');if(!s)return{success:false,message:'Vendor session expired.'};const sh=ensureSheet_(SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),MB_PORTAL.PO_SHEET,MB_PORTAL.PO_HEADERS);if(sh.getLastRow()<2)return{success:true,data:[],total:0};const rows=sh.getRange(2,1,sh.getLastRow()-1,MB_PORTAL.PO_HEADERS.length).getDisplayValues(),wanted=String(s.id).toLowerCase(),data=rows.filter(r=>String(r[3]).toLowerCase()===wanted).reverse().map(r=>({poId:r[0],createdAt:r[1],vendor:r[4],sku:r[5],productName:r[6],supplier:r[7],price:r[8],quantity:r[9],remarks:r[10],productLink:r[11],image:r[12],status:r[13]}));return{success:true,total:data.length,data:data}}
function clearVendorPurchase_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.',code:'ADMIN_SESSION'};const vendor=findVendor_(String(p.vendorId||'').trim());if(!vendor)return{success:false,message:'Vendor account not found.'};const sh=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID).getSheetByName(vendor.sheetName);if(sh&&sh.getLastRow()>1)sh.getRange(2,1,sh.getLastRow()-1,MB_PORTAL.VENDOR_HEADERS.length).clearContent();return{success:true,message:'Vendor purchase workspace cleared.'}}
function findVendor_(id){const sh=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID).getSheetByName(MB_PORTAL.VENDOR_SHEET);if(!sh||sh.getLastRow()<2)return null;const rows=sh.getRange(2,1,sh.getLastRow()-1,5).getValues();for(const r of rows)if(String(r[0]).trim()===String(id).trim())return{id:String(r[0]).trim(),name:String(r[1]),sheetName:String(r[2]),enabled:r[3]===true||String(r[3]).toLowerCase()==='true',passwordHash:String(r[4]||'')};return null}
function readVendorSheet_(sh){const last=sh.getLastRow();if(last<2)return[];const v=sh.getRange(2,1,last-1,MB_PORTAL.VENDOR_HEADERS.length).getDisplayValues();return v.map(x=>({sku:x[0],productName:x[1],quantity:x[2],supplier:x[3],productLink:x[4],image:x[5],price:x[6],remarks:x[7],poId:x[8],createdAt:x[9],status:x[10]})).filter(p=>p.sku||p.productName||p.productLink)}
function publicSyncData_(){const x=readMasterRows_(),data=x.rows.map((r,i)=>normalizeMasterProduct_(r,i+2)).filter(p=>p.sku||p.productName);return{success:true,source:'Website Listing',updated:new Date().toISOString(),data:data}}
function portalStats_(p){if(!getSession_(p.token,'admin'))return{success:false,message:'Admin session expired.'};const x=readMasterRows_(),ss=SpreadsheetApp.openById(MB_PORTAL.SPREADSHEET_ID),v=ss.getSheetByName(MB_PORTAL.VENDOR_SHEET),po=ss.getSheetByName(MB_PORTAL.PO_SHEET);return{success:true,source:'Website Listing',products:x.rows.filter(r=>String(r[MB_PORTAL.COL.SKU-1]||'').trim()).length,vendors:v?Math.max(0,v.getLastRow()-1):0,purchaseOrders:po?Math.max(0,po.getLastRow()-1):0}}
function findImage_(url){if(!/^https?:\/\//i.test(String(url||'')))return'';try{const res=UrlFetchApp.fetch(url,{muteHttpExceptions:true,followRedirects:true,timeout:10000,headers:{'User-Agent':'Mozilla/5.0'}});if(res.getResponseCode()>=400)return'';const html=res.getContentText(),patterns=[/<meta[^>]+property=["']og:image["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+name=["']twitter:image["'][^>]+content=["']([^"']+)["']/i,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:image["']/i];for(const re of patterns){const m=html.match(re);if(m&&/^https?:\/\//i.test(m[1]))return m[1]}}catch(e){}return''}
function logout_(p){if(p&&p.token)CacheService.getScriptCache().remove('MBSESSION_'+p.token);return{success:true,message:'Session terminated.'}}
function output_(obj,callback){const json=JSON.stringify(obj);if(callback&&/^[A-Za-z_$][\w$\.]*$/.test(callback))return ContentService.createTextOutput(callback+'('+json+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(json).setMimeType(ContentService.MimeType.JSON)}
function hash_(s){const b=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(s),Utilities.Charset.UTF_8);return b.map(x=>(x<0?x+256:x).toString(16).padStart(2,'0')).join('')}
function createSession_(d){const t=Utilities.getUuid().replace(/-/g,'')+Utilities.getUuid().replace(/-/g,'');CacheService.getScriptCache().put('MBSESSION_'+t,JSON.stringify(d),MB_PORTAL.SESSION_TTL);return t}
function getSession_(t,role){if(!t)return null;const raw=CacheService.getScriptCache().get('MBSESSION_'+t);if(!raw)return null;try{const s=JSON.parse(raw);return s.role===role?s:null}catch(e){return null}}
function touchSession_(t,s){CacheService.getScriptCache().put('MBSESSION_'+t,JSON.stringify(s),MB_PORTAL.SESSION_TTL)}
function onOpen(){SpreadsheetApp.getUi().createMenu('MULTYBYTE PORTAL').addItem('Setup / Repair Vendor Portal','setupVendorPortal').addItem('Reset Admin Password','resetAdminPassword').addToUi()}
